//! Python server-dispatch emit — the framework the embedded-CPython bridge (`truenas-rpc-pyo3`)
//! calls for a `python:true` body: `dispatch(name, params, session, call) -> (status, payload, audit)`.
//! It decodes `params` by the method's msgspec type (from the `METHODS` table), runs the registered
//! handler, and encodes the result. Handlers register with `@method("<wire>")` and receive a
//! `Context` (the session view + the in-process caller `call` + a settable audit detail).
//!
//! The framework is self-contained (only `msgspec` + the generated `METHODS`); the `call` byte caller
//! is the novel piece over the reference (which has no in-process call-back).

use crate::emit_py_structs::{finalize, plain_methods, py_module, types_module};
use crate::error::Result;
use crate::model::Spec;

/// Generate the server-dispatch module: `RpcError` / `Context` / the `@method` registry / the
/// `dispatch(name, params, session, call)` entry point.
pub fn generate(spec: &Spec, origin: &str) -> Result<String> {
    let module = py_module(spec)?;
    let types_mod = types_module(&module);
    // Validate the plain methods resolve (same $ref/result errors the table + client surface), so a
    // bad spec fails at server-gen too — even though the framework imports the table at runtime.
    let _ = plain_methods(spec)?;

    let mut out = String::new();
    out.push_str(&header(origin));
    out.push_str(&format!(
        "from __future__ import annotations\n\nfrom collections.abc import Callable\nfrom types import MappingProxyType\nfrom typing import Any\n\nimport msgspec\n\nfrom {types_mod} import METHODS\n\n\n"
    ));
    out.push_str(FRAMEWORK);
    Ok(finalize(out))
}

fn header(origin: &str) -> String {
    format!(
        "# GENERATED by truenas-rpc-codegen from {origin} — DO NOT EDIT BY HAND.\n#\n# The python-method dispatch framework the embedded bridge drives. Register a handler with\n# `@method(\"<wire>\")`; it receives `(request, ctx)` and returns a result the framework encodes.\n\n"
    )
}

/// The spec-independent framework body (registry + `dispatch`). Only the `from <types>_types import
/// METHODS` line above it varies per spec, so this is a fixed, deterministic block.
const FRAMEWORK: &str = r#"class RpcError(Exception):
    """Raise from a handler to return a JSON-RPC error (`code` + `message`) to the caller."""

    def __init__(self, code: int, message: str) -> None:
        super().__init__(message)
        self.code = code
        self.message = message


class Context:
    """Per-call context handed to a handler.

    ``session`` is the session-state view (raw JSON bytes); ``call`` is the in-process caller
    ``call(name: str, params: bytes, elevated: bool = False) -> bytes`` that routes back into the core
    (raising ``RuntimeError((code, message))`` on a core error); set ``audit`` to a str to attach a
    runtime audit detail.
    """

    def __init__(self, session: bytes, call: Callable[..., bytes]) -> None:
        self.session = session
        self.call = call
        self.audit: str | None = None


_HANDLERS: dict[str, Callable[..., object]] = {}

# A decoder per method's params type + one shared encoder, built once from METHODS and reused every
# call (msgspec's one-shot ``json.decode``/``encode`` rebuild these each time). A read-only proxy —
# the keys mirror METHODS, so a lookup miss is "method not found".
_DECODERS: MappingProxyType[str, msgspec.json.Decoder[Any]] = MappingProxyType(
    {name: msgspec.json.Decoder(params) for name, (params, _result) in METHODS.items()}
)
_ENCODER = msgspec.json.Encoder()


def method(name: str) -> Callable[[Callable[..., object]], Callable[..., object]]:
    """Register the decorated ``handler(request, ctx)`` for the python:true method ``name``."""

    def register(fn: Callable[..., object]) -> Callable[..., object]:
        _HANDLERS[name] = fn
        return fn

    return register


def dispatch(name: str, params: bytes, session: bytes, call: Callable[..., bytes]) -> tuple[int, bytes, bytes]:
    """The embedded-bridge entry point: look up the method, decode ``params`` by its type, run the
    handler, and encode the result. Returns ``(status, payload, audit)`` — status ``0`` with the
    result JSON as payload, or a JSON-RPC error ``code`` with the message as payload."""
    decoder = _DECODERS.get(name)
    handler = _HANDLERS.get(name)
    if decoder is None or handler is None:
        return (-32601, b"Method not found", b"")
    try:
        request = decoder.decode(params)
    except (msgspec.ValidationError, msgspec.DecodeError) as exc:
        return (-32602, str(exc).encode(), b"")
    ctx = Context(session, call)
    try:
        result = handler(request, ctx)
    except RpcError as exc:
        return (exc.code, str(exc.message).encode(), b"")
    audit = ctx.audit.encode() if ctx.audit else b""
    return (0, _ENCODER.encode(result), audit)
"#;
