//! Server emit — a `Handlers<S>` trait (the consumer's binding point; a missing/mistyped method is a
//! compile error) + a `register()` that wires each method onto the core's builder, over the shared
//! `$defs` types (see [`crate::emit_types`]). Fully-qualified paths (`truenas_rpc::…`, `serde::…`) so
//! the `include!`d output needs no `use`.

use crate::error::{CodegenError, Result};
use crate::model::{Direction, MethodSpec, SchemaNode, Spec, TransferKind};
use crate::typemap::{ref_name, str_lit};

/// Generate the server module (`Handlers` trait + `register()` + `PYTHON_METHODS`).
pub fn generate(spec: &Spec, origin: &str) -> Result<String> {
    let mut out = String::new();
    out.push_str(&header(origin));
    out.push_str(&emit_handlers_trait(spec)?);
    out.push('\n');
    out.push_str(&emit_register(spec)?);
    out.push_str(&emit_audit(spec));
    out.push_str(&emit_python_table(spec));
    out.push_str(&emit_protocols(spec));
    Ok(out)
}

fn header(origin: &str) -> String {
    format!(
        "// GENERATED by truenas-rpc-codegen from {origin} — DO NOT EDIT BY HAND.\n//\n// A `Handlers` trait + `register()` over the shared `$defs` types (see `types_gen.rs`). Implement\n// `Handlers<S>` for your server-state type and pass it to `register`; a missing/mistyped handler is\n// a compile error.\n\n"
    )
}

/// Kinds of method (drives the trait method + register line).
enum Kind {
    Plain,
    Async,
    Filterable,
    Subscription,
    Python,
    Transfer,
}

fn kind_of(m: &MethodSpec) -> Kind {
    if m.transfer.is_some() {
        Kind::Transfer // exclusive with every other kind (enforced by validate)
    } else if m.python {
        Kind::Python
    } else if m.direction() == Direction::ServerClient {
        Kind::Subscription
    } else if m.filterable {
        Kind::Filterable
    } else if m.is_async {
        Kind::Async
    } else {
        Kind::Plain
    }
}

/// The Rust type of a transfer's interim (`$/transferReady`): the declared `ready` ref's type, or
/// `serde_json::Value` when the IDL leaves it free-form (matching the reference client).
fn transfer_ready_ty(m: &MethodSpec) -> Result<String> {
    match m.transfer.as_ref().and_then(|t| t.ready.as_ref()) {
        Some(node) => ref_name_of(node, "transfer.ready"),
        None => Ok("serde_json::Value".to_string()),
    }
}

/// The `TransferDirection` variant name for a transfer method.
fn transfer_direction(m: &MethodSpec) -> &'static str {
    match m
        .transfer
        .as_ref()
        .expect("transfer present (kind is Transfer)")
        .direction
    {
        TransferKind::Download => "Download",
        TransferKind::Upload => "Upload",
    }
}

fn emit_handlers_trait(spec: &Spec) -> Result<String> {
    let mut methods = String::new();
    for (_, m) in spec.methods.iter() {
        let params = ref_name_of(&m.params, "params")?;
        match kind_of(m) {
            Kind::Plain => {
                let result = ref_name_of(
                    m.result.as_ref().ok_or_else(|| miss(m, "result"))?,
                    "result",
                )?;
                methods.push_str(&format!(
                    "    /// Handler for `{}`.\n    fn {}(&self, request: {params}, cx: &truenas_rpc::RequestCtx<S>) -> Result<{result}, truenas_rpc::JsonRpcError>;\n",
                    wire_doc(spec, m), m.handler
                ));
            }
            Kind::Async => {
                let result = ref_name_of(
                    m.result.as_ref().ok_or_else(|| miss(m, "result"))?,
                    "result",
                )?;
                // RPITIT (`-> impl Future + Send`, stable since 1.75) — no `async-trait` dep on the
                // generated code. Implement it with `async fn {handler}(..)`. `cx` is by value (the
                // future is awaited on the runtime, not borrowing the dispatch frame).
                methods.push_str(&format!(
                    "    /// Async handler for `{}`.\n    fn {}(&self, request: {params}, cx: truenas_rpc::RequestCtx<S>) -> impl ::core::future::Future<Output = Result<{result}, truenas_rpc::JsonRpcError>> + Send;\n",
                    wire_doc(spec, m), m.handler
                ));
            }
            Kind::Filterable => {
                let entry = ref_name_of(
                    m.entry
                        .as_ref()
                        .expect("filterable entry present (guaranteed by validate)"),
                    "entry",
                )?;
                methods.push_str(&format!(
                    "    /// Filterable handler for `{}`.\n    fn {}(&self, request: {params}, cx: &truenas_rpc::RequestCtx<S>, filters: &truenas_rpc::CompiledFilters, options: &truenas_rpc::CompiledOptions) -> Result<truenas_rpc::Filtered<{entry}>, truenas_rpc::JsonRpcError>;\n",
                    wire_doc(spec, m), m.handler
                ));
            }
            Kind::Transfer => {
                // Two callbacks: `negotiate` (returns the `$/transferReady` interim) and the
                // `transfer` itself (lent the raw fd → the final result).
                let result = ref_name_of(
                    m.result.as_ref().ok_or_else(|| miss(m, "result"))?,
                    "result",
                )?;
                let ready = transfer_ready_ty(m)?;
                let doc = wire_doc(spec, m);
                let handler = &m.handler;
                methods.push_str(&format!(
                    "    /// Transfer `negotiate` for `{doc}` — validate the request, return the `$/transferReady` interim.\n    fn {handler}_ready(&self, request: &{params}, cx: &truenas_rpc::RequestCtx<S>) -> Result<{ready}, truenas_rpc::JsonRpcError>;\n    /// Transfer handler for `{doc}` — lent the connection's raw fd, produce the final result.\n    fn {handler}(&self, request: {params}, ft: &dyn truenas_rpc::FileTransfer) -> Result<{result}, truenas_rpc::JsonRpcError>;\n",
                ));
            }
            Kind::Subscription | Kind::Python => {} // no trait method
        }
    }
    Ok(format!(
        "/// Implement for your server-state type `S`: one method per request/filterable RPC.\npub trait Handlers<S>: Send + Sync {{\n{methods}}}\n"
    ))
}

fn emit_register(spec: &Spec) -> Result<String> {
    let mut body = String::new();
    let mut uses_handlers = false;
    for (wire, m) in spec.methods.iter() {
        let def = method_def_expr(spec, wire, m);
        match kind_of(m) {
            Kind::Plain => {
                uses_handlers = true;
                let params = ref_name_of(&m.params, "params")?;
                body.push_str(&format!(
                    "    let h = handlers.clone();\n    let builder = builder.method(truenas_rpc::RpcMethod::new({def}, move |request: {params}, cx: &truenas_rpc::RequestCtx<S>| h.{}(request, cx)))?;\n",
                    m.handler
                ));
            }
            Kind::Async => {
                uses_handlers = true;
                let params = ref_name_of(&m.params, "params")?;
                // Clone the `Arc<H>` into each invocation's future so it owns its handle (a `Fn`
                // closure can't move its capture), and await the handler inline on the runtime.
                body.push_str(&format!(
                    "    let h = handlers.clone();\n    let builder = builder.async_method(truenas_rpc::AsyncRpcMethod::new({def}, move |request: {params}, cx: truenas_rpc::RequestCtx<S>| {{\n        let h = h.clone();\n        async move {{ h.{}(request, cx).await }}\n    }}))?;\n",
                    m.handler
                ));
            }
            Kind::Filterable => {
                uses_handlers = true;
                let params = ref_name_of(&m.params, "params")?;
                let entry = ref_name_of(
                    m.entry
                        .as_ref()
                        .expect("filterable entry present (guaranteed by validate)"),
                    "entry",
                )?;
                body.push_str(&format!(
                    "    let h = handlers.clone();\n    let builder = builder.filterable(truenas_rpc::FilterableRpcMethod::<{params}, {entry}, _>::new({def}, move |request: {params}, cx: &truenas_rpc::RequestCtx<S>, filters: &truenas_rpc::CompiledFilters, options: &truenas_rpc::CompiledOptions| h.{}(request, cx, filters, options)))?;\n",
                    m.handler
                ));
            }
            Kind::Subscription => {
                let params = ref_name_of(&m.params, "params")?;
                let notifies = ref_name_of(
                    m.notifies.as_ref().ok_or_else(|| miss(m, "notifies"))?,
                    "notifies",
                )?;
                body.push_str(&format!(
                    "    let builder = builder.subscription(truenas_rpc::SubscriptionDef::<{params}, {notifies}>::new({def}))?;\n"
                ));
            }
            Kind::Python => {
                body.push_str(&format!(
                    "    let builder = builder.python_method({def})?;\n"
                ));
            }
            Kind::Transfer => {
                uses_handlers = true;
                let params = ref_name_of(&m.params, "params")?;
                let result = ref_name_of(
                    m.result.as_ref().ok_or_else(|| miss(m, "result"))?,
                    "result",
                )?;
                let ready = transfer_ready_ty(m)?;
                let dir = transfer_direction(m);
                let handler = &m.handler;
                body.push_str(&format!(
                    "    let h = handlers.clone();\n    let builder = builder.fd_transfer_method(truenas_rpc::RpcFdTransferMethod::<{params}, {ready}, {result}, _, _>::new({def}, truenas_rpc::TransferDirection::{dir}, {{ let h = h.clone(); move |request: &{params}, cx: &truenas_rpc::RequestCtx<S>| h.{handler}_ready(request, cx) }}, move |request: {params}, ft: &dyn truenas_rpc::FileTransfer| h.{handler}(request, ft)))?;\n"
                ));
            }
        }
    }
    let prelude = if uses_handlers {
        ""
    } else {
        "    let _ = &handlers;\n"
    };
    // On by default: install the spec-configured audit sink (empty identity — override via
    // `make_audit_sink`). Emitted only when auditing is enabled (so a disabled spec needs no
    // `truenas-audit` dependency).
    let audit_install = if spec.resolved_audit().is_some() {
        "    let builder = builder.audit_sink(make_audit_sink::<S, _>(|_session: &truenas_rpc::Session<S>| truenas_rpc_utils_unsafe::audit::AuditPrincipal::default()));\n"
    } else {
        ""
    };
    Ok(format!(
        "/// Register every spec method onto `builder`, binding each to `handlers.<handler>`.\npub fn register<S, H>(\n    builder: truenas_rpc::JsonRpcProtocolBuilder<S>,\n    handlers: std::sync::Arc<H>,\n) -> truenas_rpc::BuildResult<truenas_rpc::JsonRpcProtocolBuilder<S>>\nwhere\n    S: Send + Sync + 'static,\n    H: Handlers<S> + 'static,\n{{\n{prelude}{body}{audit_install}    Ok(builder)\n}}\n"
    ))
}

/// Emit the `make_audit_sink` helper — only when auditing is enabled. It carries the spec's
/// configured `service` + `queueBound`; the consumer supplies the identity extractor.
fn emit_audit(spec: &Spec) -> String {
    let Some(audit) = spec.resolved_audit() else {
        return String::new();
    };
    let queue = match audit.queue_bound {
        Some(n) => format!(".queue_bound({n}usize)"),
        None => String::new(),
    };
    format!(
        "\n/// Build the spec-configured Linux kernel-audit sink with your identity extractor.\n/// `register` installs one with an empty extractor by default; pass an extractor that reads your\n/// session state and re-install via `.audit_sink(..)` to attribute records (`acct=`, uid, origin).\npub fn make_audit_sink<S, F>(identity: F) -> truenas_rpc_utils_unsafe::audit::LinuxAuditSink<S>\nwhere\n    S: Send + Sync + 'static,\n    F: Fn(&truenas_rpc::Session<S>) -> truenas_rpc_utils_unsafe::audit::AuditPrincipal + Send + Sync + 'static,\n{{\n    truenas_rpc_utils_unsafe::audit::LinuxAuditSink::<S>::builder({service}){queue}.identity(identity).build()\n}}\n",
        service = str_lit(&audit.service),
    )
}

/// The declared wire protocols as a const, plus — when `onc-rpc` is declared — the default ONC RPC
/// program/version so a consumer can wire `OncRpc::protocol(name).at(ONC_PROGRAM, ONC_VERSION)`
/// without magic numbers. The program/version are generic RFC 5531 user-range defaults (a server-wiring
/// concern, kept out of the IDL); override them per listener.
fn emit_protocols(spec: &Spec) -> String {
    let lits: Vec<String> = spec.protocols.iter().map(|p| str_lit(p)).collect();
    let mut out = format!(
        "\n/// The wire protocols this service is served over (from the json-idl `protocols`).\npub const PROTOCOLS: &[&str] = &[{}];\n",
        lits.join(", ")
    );
    if spec.protocols.iter().any(|p| p == "onc-rpc") {
        out.push_str(
            "\n/// Default ONC RPC program/version this service answers to (override per listener).\npub const ONC_PROGRAM: u32 = 0x2000_0001;\npub const ONC_VERSION: u32 = 1;\n",
        );
    }
    out
}

fn emit_python_table(spec: &Spec) -> String {
    let names: Vec<String> = spec
        .methods
        .iter()
        .filter(|(_, m)| m.python)
        .map(|(w, _)| str_lit(w))
        .collect();
    if names.is_empty() {
        String::new()
    } else {
        format!(
            "\n/// The `python:true` methods (bodies run via the PyO3 bridge, not `Handlers`).\npub const PYTHON_METHODS: &[&str] = &[{}];\n",
            names.join(", ")
        )
    }
}

fn method_def_expr(spec: &Spec, wire: &str, m: &MethodSpec) -> String {
    let mut s = format!("truenas_rpc::MethodDef::new({})", str_lit(wire));
    if let Some(doc) = &m.summary {
        s.push_str(&format!(".doc({})", str_lit(doc)));
    }
    if m.pre_auth {
        s.push_str(".pre_auth()");
    }
    if let Some(msg) = &m.audit_message {
        s.push_str(&format!(".audit_message({})", str_lit(msg)));
    } else if m.audit {
        s.push_str(".audit()");
    }
    if m.cancellable {
        s.push_str(".cancellable()");
    }
    if !m.roles.is_empty() {
        let roles: Vec<String> = m.roles.iter().map(|r| str_lit(r)).collect();
        s.push_str(&format!(".roles([{}])", roles.join(", ")));
    }
    let secrets = secret_param_fields(spec, m);
    if !secrets.is_empty() {
        let lits: Vec<String> = secrets.iter().map(|f| str_lit(f)).collect();
        s.push_str(&format!(".secret_fields([{}])", lits.join(", ")));
    }
    if m.xdr {
        if let Some(id) = m.xdr_id {
            s.push_str(&format!(".xdr({id}u32)"));
        }
    }
    if let Some(cap) = reply_capacity(spec, m) {
        s.push_str(&format!(".reply_capacity({cap})"));
    }
    s
}

/// ~ the JSON-RPC reply envelope skeleton `{"jsonrpc":"2.0","result":<>,"id":"<36-char uuid>"}`.
const REPLY_ENVELOPE_BYTES: usize = 72;

/// A generous estimate of the JSON bytes a value of `node`'s shape serializes to — used only to
/// pre-size the reply buffer (`MethodDef::reply_capacity`). Over-estimating reserves a few extra
/// bytes once; under-estimating costs one realloc. Fixed-shape types (integers/bools/fixed objects)
/// land near-exact; variable ones (strings/arrays) get a typical-small allowance. `$ref`s resolve
/// through `spec.defs`, recursion-guarded.
fn json_value_bytes(node: &SchemaNode, spec: &Spec, depth: usize) -> usize {
    if depth > 8 {
        return 16;
    }
    if let Some(r) = &node.reference {
        if let Ok(name) = ref_name(r) {
            if let Some(d) = spec.defs.get(&name) {
                return json_value_bytes(d, spec, depth + 1);
            }
        }
        return 16;
    }
    match node.ty.as_deref() {
        Some("integer") => 20, // i64 text + sign
        Some("number") => 24,
        Some("boolean") => 5,
        Some("string") => 24, // "<short string>"; content variable
        Some("array") => {
            2 + node
                .items
                .as_ref()
                .map_or(16, |it| json_value_bytes(it, spec, depth + 1))
        }
        Some("object") => {
            2 + node
                .properties
                .iter()
                .map(|(name, p)| name.len() + 4 + json_value_bytes(p, spec, depth + 1))
                .sum::<usize>()
        }
        _ => 16, // enum / unknown
    }
}

/// The per-method reply-buffer reservation: the JSON-RPC envelope plus its result (or, for a
/// filterable method, one `entry`). `None` for methods with no result/entry (subscription, python,
/// transfer), which keep the default unsized buffer.
fn reply_capacity(spec: &Spec, m: &MethodSpec) -> Option<usize> {
    let node = m.result.as_ref().or(m.entry.as_ref())?;
    Some(REPLY_ENVELOPE_BYTES + json_value_bytes(node, spec, 0))
}

/// The wire-names of the secret properties in a method's params `$def` (fed to
/// `MethodDef::secret_fields` for the core's name-based audit redaction).
fn secret_param_fields(spec: &Spec, m: &MethodSpec) -> Vec<String> {
    let Some(reference) = &m.params.reference else {
        return Vec::new();
    };
    let Ok(name) = ref_name(reference) else {
        return Vec::new();
    };
    let Some(def) = spec.defs.get(&name) else {
        return Vec::new();
    };
    def.properties
        .iter()
        .filter(|(_, p)| p.secret)
        .map(|(k, _)| k.to_string())
        .collect()
}

fn ref_name_of(node: &SchemaNode, slot: &str) -> Result<String> {
    match &node.reference {
        Some(r) => ref_name(r),
        None => Err(CodegenError::new(format!(
            "{slot} must be a $ref to a $def"
        ))),
    }
}

fn miss(m: &MethodSpec, slot: &str) -> CodegenError {
    CodegenError::new(format!(
        "method with handler {:?} is missing '{slot}'",
        m.handler
    ))
}

fn wire_doc(_spec: &Spec, m: &MethodSpec) -> String {
    m.handler.clone()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn spec(defs: serde_json::Value) -> Spec {
        serde_json::from_value(serde_json::json!({
            "name": "t",
            "version": "1",
            "$defs": defs,
            "methods": {},
        }))
        .expect("minimal spec deserializes")
    }

    /// The `json_value_bytes` arms the golden specs don't reach: a self-referential `$ref` (the
    /// recursion guard), an unresolved `$ref`, and a typeless/unknown node — each returns the
    /// catch-all 16-byte default.
    #[test]
    fn reply_capacity_size_walker_guards_and_defaults() {
        let s = spec(serde_json::json!({ "A": { "$ref": "#/$defs/A" } }));

        let self_ref = SchemaNode {
            reference: Some("#/$defs/A".to_string()),
            ..Default::default()
        };
        assert_eq!(
            json_value_bytes(&self_ref, &s, 0),
            16,
            "recursion guard (depth > 8)"
        );

        let dangling = SchemaNode {
            reference: Some("#/$defs/Missing".to_string()),
            ..Default::default()
        };
        assert_eq!(
            json_value_bytes(&dangling, &s, 0),
            16,
            "unresolved $ref (name resolves, def absent)"
        );

        let malformed = SchemaNode {
            reference: Some("#/components/Foo".to_string()),
            ..Default::default()
        };
        assert_eq!(
            json_value_bytes(&malformed, &s, 0),
            16,
            "malformed $ref (ref_name errors)"
        );

        assert_eq!(
            json_value_bytes(&SchemaNode::default(), &s, 0),
            16,
            "unknown / typeless node"
        );
    }
}
