//! Python API-types emit — one `msgspec.Struct` per `$defs`, the generated `enum.StrEnum`s, and a
//! `METHODS` table (wire name → `(Params, Result)`) shared by the generated client and the
//! server-dispatch shim. Emits `.py` **text** (no pyo3, no runtime dependency on this crate);
//! conventions mirror the reference `truenas_jsonrpc` python (`from __future__ import annotations`,
//! `Annotated[T, msgspec.Meta(extra={"secret": True})]` for secrets, required-before-defaulted
//! fields).
//!
//! Also the home of the shared Python-naming/type helpers the sibling `emit_py_client` /
//! `emit_py_server` emitters reuse.

use serde_json::Value;

use crate::error::{CodegenError, Result};
use crate::model::{Direction, MethodSpec, SchemaNode, Spec};
use crate::naming::{is_ident, pascal_case};
use crate::typemap::{ref_name, str_lit};

/// Generate the API-types module: the `$defs` structs, any generated `StrEnum`s, and the `METHODS`
/// table.
pub fn generate(spec: &Spec, origin: &str) -> Result<String> {
    let mut ctx = PyCtx::default();
    let mut structs: Vec<String> = Vec::new();
    for (name, schema) in spec.defs.iter() {
        structs.push(emit_struct(name, schema, &mut ctx)?);
    }

    // Top-level blocks in emit order: enums, then structs, then the METHODS table — each already
    // ends with a newline, so joining with "\n\n" leaves 2 blank lines between (PEP 8).
    let mut blocks: Vec<String> = ctx.enums.iter().map(|(_, d)| d.clone()).collect();
    blocks.extend(structs);
    blocks.push(emit_methods_table(spec)?);

    let mut out = String::new();
    out.push_str(&header(origin));
    out.push_str(&imports(!ctx.enums.is_empty(), ctx.secret_seen));
    out.push_str("\n\n");
    out.push_str(&blocks.join("\n\n"));
    Ok(finalize(out))
}

/// Normalize a generated module to end with exactly one trailing newline (no trailing blank lines).
pub(crate) fn finalize(s: String) -> String {
    format!("{}\n", s.trim_end())
}

fn header(origin: &str) -> String {
    format!(
        "# GENERATED by truenas-rpc-codegen from {origin} — DO NOT EDIT BY HAND.\n#\n# The msgspec API types (one class per `$defs`), the generated `StrEnum`s, and a `METHODS` table\n# (wire name -> (Params, Result)) shared by the generated client and the server-dispatch shim.\n\n"
    )
}

/// The import preamble (PEP 8 grouped: future, stdlib, third-party), ending with the `import
/// msgspec` line's newline. The stdlib group always carries `MappingProxyType` (`METHODS` is a
/// read-only proxy); `enum` / `typing.Annotated` only when the spec uses a `StrEnum` / a secret.
fn imports(has_enum: bool, has_secret: bool) -> String {
    let mut out = String::from("from __future__ import annotations\n\n");
    if has_enum {
        out.push_str("import enum\n");
    }
    out.push_str("from types import MappingProxyType\n");
    if has_secret {
        out.push_str("from typing import Annotated\n");
    }
    out.push('\n');
    out.push_str("import msgspec\n");
    out
}

/// Accumulates the generated `StrEnum` definitions (first-seen order, deduped) and whether any
/// secret field was emitted (to decide the `Annotated` import).
#[derive(Default)]
struct PyCtx {
    enums: Vec<(String, String)>,
    secret_seen: bool,
}

impl PyCtx {
    fn add_enum(&mut self, name: &str, def: String) {
        if !self.enums.iter().any(|(n, _)| n == name) {
            self.enums.push((name.to_string(), def));
        }
    }
}

/// One `class <Name>(msgspec.Struct)`. Fields are emitted **required-first, then defaulted/optional**
/// (msgspec, like dataclasses, forbids a required field after a defaulted one); document order is
/// preserved within each group.
fn emit_struct(name: &str, schema: &SchemaNode, ctx: &mut PyCtx) -> Result<String> {
    if schema.ty.as_deref() != Some("object") {
        return Err(CodegenError::new(format!(
            "$defs.{name} must be a JSON object schema (got type={:?})",
            schema.ty
        )));
    }
    let mut required = String::new();
    let mut defaulted = String::new();
    for (pname, pschema) in schema.properties.iter() {
        let ident = py_field_ident(name, pname)?;
        let hint = format!("{name}{}", pascal_case(pname));
        let ty = py_type(pschema, &hint, ctx)?;
        if let Some(default) = &pschema.default {
            let rendered = render_default(pschema, &ty, default)?;
            defaulted.push_str(&format!("    {ident}: {ty} = {rendered}\n"));
        } else if schema.required.iter().any(|r| r == pname) {
            required.push_str(&format!("    {ident}: {ty}\n"));
        } else {
            defaulted.push_str(&format!("    {ident}: {ty} | None = None\n"));
        }
    }
    let body = format!("{required}{defaulted}");
    if body.is_empty() {
        Ok(format!("class {name}(msgspec.Struct):\n    pass\n"))
    } else {
        Ok(format!("class {name}(msgspec.Struct):\n{body}"))
    }
}

/// The Python type for a schema node — a `$ref` type, a generated `StrEnum` (named `<Struct><Field>`
/// via `name_hint`), a scalar, or `list[T]`. A secret wraps in `Annotated[T, msgspec.Meta(...)]`.
fn py_type(node: &SchemaNode, name_hint: &str, ctx: &mut PyCtx) -> Result<String> {
    let base = if let Some(reference) = &node.reference {
        ref_name(reference)?
    } else if let Some(values) = &node.enum_values {
        let name = name_hint.to_string();
        let def = emit_enum(&name, values)?;
        ctx.add_enum(&name, def);
        name
    } else {
        match node.ty.as_deref() {
            Some("string") => "str".to_string(),
            Some("integer") => "int".to_string(),
            Some("number") => "float".to_string(),
            Some("boolean") => "bool".to_string(),
            Some("array") => {
                let items = node
                    .items
                    .as_deref()
                    .ok_or_else(|| CodegenError::new("array schema must have an object 'items'"))?;
                format!(
                    "list[{}]",
                    py_type(items, &format!("{name_hint}Item"), ctx)?
                )
            }
            Some("object") => {
                return Err(CodegenError::new(
                    "inline object types aren't supported; use a $ref to a $def",
                ))
            }
            other => {
                return Err(CodegenError::new(format!(
                    "unsupported schema (need $ref, enum, or a known type), got type={other:?}"
                )))
            }
        }
    };
    Ok(if node.secret {
        ctx.secret_seen = true;
        format!("Annotated[{base}, msgspec.Meta(extra={{\"secret\": True}})]")
    } else {
        base
    })
}

fn emit_enum(name: &str, values: &[Value]) -> Result<String> {
    if values.is_empty() {
        return Err(CodegenError::new(format!(
            "enum {name:?} must have at least one value"
        )));
    }
    let mut members = String::new();
    for v in values {
        let s = v.as_str().ok_or_else(|| {
            CodegenError::new(format!("enum {name:?} values must all be strings"))
        })?;
        let member = screaming_snake(s);
        if member.is_empty() {
            return Err(CodegenError::new(format!(
                "enum {name:?} value {s:?} has no identifier characters"
            )));
        }
        members.push_str(&format!("    {member} = {}\n", str_lit(s)));
    }
    Ok(format!("class {name}(enum.StrEnum):\n{members}"))
}

/// Render a field default as a Python literal (`0`, `1.5`, `True`, `"anon"`, a `StrEnum` member, or a
/// `default_factory` for the empty-array case).
fn render_default(pschema: &SchemaNode, ty: &str, default: &Value) -> Result<String> {
    if pschema.enum_values.is_some() {
        let s = default
            .as_str()
            .ok_or_else(|| CodegenError::new("enum default must be a string"))?;
        return Ok(format!("{ty}.{}", screaming_snake(s)));
    }
    match pschema.ty.as_deref() {
        Some("string") => {
            let s = default
                .as_str()
                .ok_or_else(|| CodegenError::new("string default must be a string"))?;
            Ok(str_lit(s))
        }
        Some("integer") => {
            let n = default
                .as_i64()
                .ok_or_else(|| CodegenError::new("integer default must be an integer"))?;
            Ok(format!("{n}"))
        }
        Some("number") => {
            let f = default
                .as_f64()
                .ok_or_else(|| CodegenError::new("number default must be a number"))?;
            Ok(format!("{f:?}"))
        }
        Some("boolean") => {
            let b = default
                .as_bool()
                .ok_or_else(|| CodegenError::new("boolean default must be a boolean"))?;
            Ok(if b {
                "True".to_string()
            } else {
                "False".to_string()
            })
        }
        Some("array") => {
            if !default.as_array().is_some_and(|a| a.is_empty()) {
                return Err(CodegenError::new(
                    "only an empty-array default ([]) is supported",
                ));
            }
            Ok("msgspec.field(default_factory=list)".to_string())
        }
        other => Err(CodegenError::new(format!(
            "unsupported default for type {other:?}"
        ))),
    }
}

/// `METHODS`: each plain `request -> result` method's wire name → its `(Params, Result)` types. The
/// server-dispatch shim decodes params by `METHODS[name][0]`; the client types its methods from it.
/// Subscriptions / filterable / transfer methods have no single `(Params, Result)` pair and are
/// skipped (the same filter the client uses).
fn emit_methods_table(spec: &Spec) -> Result<String> {
    let mut rows = String::new();
    for m in plain_methods(spec)? {
        rows.push_str(&format!(
            "    {}: ({}, {}),\n",
            str_lit(m.wire),
            m.params,
            m.result
        ));
    }
    Ok(format!(
        "METHODS: MappingProxyType[str, tuple[type, type]] = MappingProxyType({{\n{rows}}})\n"
    ))
}

// --- shared helpers (reused by emit_py_client / emit_py_server) --------------

/// A plain `client_server` `request -> result` method (not a subscription / filterable / transfer),
/// with its params/result `$def` type names resolved. Used to build the `METHODS` table and to
/// validate the spec at server-gen; the client iterates `spec.methods` directly (to interleave the
/// skipped-method comments in wire order).
pub(crate) struct PlainMethod<'a> {
    pub wire: &'a str,
    pub params: String,
    pub result: String,
}

/// Whether `m` is a plain `request -> result` method (the shape a single `(Params, Result)` row /
/// typed client method needs). Python-backed methods qualify (they carry a normal params/result).
pub(crate) fn is_plain_method(m: &MethodSpec) -> bool {
    m.direction() == Direction::ClientServer && !m.filterable && m.transfer.is_none()
}

/// The plain methods in wire order, each with its `$ref` params/result resolved (errors on an
/// inline/missing type — the same validation the client and dispatch table share).
pub(crate) fn plain_methods(spec: &Spec) -> Result<Vec<PlainMethod<'_>>> {
    let mut out = Vec::new();
    for (wire, m) in spec.methods.iter() {
        if !is_plain_method(m) {
            continue;
        }
        let params = ref_name_of(&m.params, "params")?;
        let result = ref_name_of(m.result.as_ref().ok_or_else(|| miss("result"))?, "result")?;
        out.push(PlainMethod {
            wire,
            params,
            result,
        });
    }
    Ok(out)
}

/// The Python module identifier for the spec (the service `name`), **sanitized** so a versioned /
/// dotted name works: each non-`[A-Za-z0-9_]` char → `_`, a leading digit → `_`-prefixed. So
/// `api.v1` → `api_v1`. Errors only when nothing usable remains (e.g. an empty name).
pub(crate) fn py_module(spec: &Spec) -> Result<String> {
    let mut out: String = spec
        .name
        .chars()
        .map(|c| {
            if c == '_' || c.is_ascii_alphanumeric() {
                c
            } else {
                '_'
            }
        })
        .collect();
    if out.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        out.insert(0, '_');
    }
    if out.is_empty() {
        return Err(CodegenError::new(format!(
            "spec name {:?} has no characters usable in a Python module identifier",
            spec.name
        )));
    }
    Ok(out)
}

/// The generated API-types module name (`<module>_types`) the client/server import from.
pub(crate) fn types_module(module: &str) -> String {
    format!("{module}_types")
}

/// The generated client class name (`<Pascal>Client`), e.g. `sample` → `SampleClient`.
pub(crate) fn client_class(spec: &Spec) -> String {
    format!("{}Client", pascal_case(&spec.name))
}

/// Resolve a `$ref` node to its `$def` name, or error that `slot` must be a `$ref`.
pub(crate) fn ref_name_of(node: &SchemaNode, slot: &str) -> Result<String> {
    match &node.reference {
        Some(r) => ref_name(r),
        None => Err(CodegenError::new(format!(
            "{slot} must be a $ref to a $def"
        ))),
    }
}

pub(crate) fn miss(slot: &str) -> CodegenError {
    CodegenError::new(format!("missing '{slot}'"))
}

/// A struct field name → a validated Python identifier (the json-idl identifier rule; the dialect
/// has no keyword-remapping, so a non-identifier is an error).
fn py_field_ident(struct_name: &str, pname: &str) -> Result<String> {
    if is_ident(pname) {
        Ok(pname.to_string())
    } else {
        Err(CodegenError::new(format!(
            "$defs.{struct_name} property {pname:?} is not a valid identifier"
        )))
    }
}

/// `SCREAMING_SNAKE_CASE` for a `StrEnum` member (non-alphanumeric runs are word breaks; a leading
/// digit is `_`-prefixed to stay a valid identifier). `""` if the value has no identifier chars.
fn screaming_snake(s: &str) -> String {
    let mut out = String::new();
    let mut pending_sep = false;
    for c in s.chars() {
        if c.is_ascii_alphanumeric() {
            if pending_sep && !out.is_empty() {
                out.push('_');
            }
            out.extend(c.to_uppercase());
            pending_sep = false;
        } else {
            pending_sep = true;
        }
    }
    if out.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        out.insert(0, '_');
    }
    out
}
