//! TypeScript API-types emit — one `export interface` per `$defs`, a string-union `type` alias per
//! generated enum. Emits `.ts` **text** (no runtime dep on this crate). The type shape mirrors the
//! Python msgspec structs (`emit_py_structs`): the same `$ref` / enum / optional / secret handling,
//! rendered in TypeScript (`JSON.parse` is structural, so there is no `METHODS`/decoder table).
//!
//! Also the home of the shared TS naming helpers the sibling `emit_ts_client` emitter reuses.

use serde_json::Value;

use crate::emit_py_structs::finalize;
use crate::error::{CodegenError, Result};
use crate::model::{SchemaNode, Spec};
use crate::naming::{is_ident, pascal_case};
use crate::typemap::{ref_name, str_lit};

/// Generate the API-types module: an `interface` per `$def` and a string-union `type` per enum.
pub fn generate(spec: &Spec, origin: &str) -> Result<String> {
    let mut ctx = TsCtx::default();
    let mut interfaces: Vec<String> = Vec::new();
    for (name, schema) in spec.defs.iter() {
        interfaces.push(emit_interface(name, schema, &mut ctx)?);
    }

    // Enum aliases first, then the interfaces — each block already ends with a newline, so joining
    // with "\n" leaves exactly one blank line between top-level declarations.
    let mut blocks: Vec<String> = ctx.enums.iter().map(|(_, d)| d.clone()).collect();
    blocks.extend(interfaces);

    let mut out = String::new();
    out.push_str(&header(origin));
    out.push_str(&blocks.join("\n"));
    Ok(finalize(out))
}

fn header(origin: &str) -> String {
    format!(
        "// GENERATED by truenas-rpc-codegen from {origin} — DO NOT EDIT BY HAND.\n//\n// The TypeScript API types: one `interface` per `$defs`, a string-union `type` per enum. Imported\n// by the generated client; safe to import on their own for a types-only consumer.\n\n"
    )
}

/// Accumulates the generated string-union enum aliases (first-seen order, deduped by name).
#[derive(Default)]
struct TsCtx {
    enums: Vec<(String, String)>,
}

impl TsCtx {
    fn add_enum(&mut self, name: &str, def: String) {
        if !self.enums.iter().any(|(n, _)| n == name) {
            self.enums.push((name.to_string(), def));
        }
    }
}

/// One `export interface <Name>`. Document (property) order is preserved (TS has no required-before-
/// optional constraint). A field is optional (`?`) when it has a default or is not `required`; a
/// non-required, non-defaulted field also admits `null`. A `secret` field gets a `/** secret */` doc.
fn emit_interface(name: &str, schema: &SchemaNode, ctx: &mut TsCtx) -> Result<String> {
    if schema.ty.as_deref() != Some("object") {
        return Err(CodegenError::new(format!(
            "$defs.{name} must be a JSON object schema (got type={:?})",
            schema.ty
        )));
    }
    let mut fields = String::new();
    for (pname, pschema) in schema.properties.iter() {
        if !is_ident(pname) {
            return Err(CodegenError::new(format!(
                "$defs.{name} property {pname:?} is not a valid identifier"
            )));
        }
        let hint = format!("{name}{}", pascal_case(pname));
        let ty = ts_type(pschema, &hint, ctx)?;
        if pschema.secret {
            fields.push_str("  /** secret */\n");
        }
        let has_default = pschema.default.is_some();
        let required = schema.required.iter().any(|r| r == pname);
        if has_default || !required {
            let ty = if has_default {
                ty
            } else {
                format!("{ty} | null")
            };
            fields.push_str(&format!("  {pname}?: {ty};\n"));
        } else {
            fields.push_str(&format!("  {pname}: {ty};\n"));
        }
    }
    if fields.is_empty() {
        Ok(format!("export interface {name} {{}}\n"))
    } else {
        Ok(format!("export interface {name} {{\n{fields}}}\n"))
    }
}

/// The TypeScript type for a schema node — a `$ref` interface, a generated string-union enum alias
/// (named `<Struct><Field>` via `name_hint`), a scalar, or `T[]`. Secrets are metadata-only (a JSDoc
/// on the field), so they don't change the type here.
fn ts_type(node: &SchemaNode, name_hint: &str, ctx: &mut TsCtx) -> Result<String> {
    if let Some(reference) = &node.reference {
        ref_name(reference)
    } else if let Some(values) = &node.enum_values {
        let name = name_hint.to_string();
        let def = emit_enum_alias(&name, values)?;
        ctx.add_enum(&name, def);
        Ok(name)
    } else {
        match node.ty.as_deref() {
            Some("string") => Ok("string".to_string()),
            // JSON has no integer/float distinction on the wire — both are `number`.
            Some("integer") | Some("number") => Ok("number".to_string()),
            Some("boolean") => Ok("boolean".to_string()),
            Some("array") => {
                let items = node
                    .items
                    .as_deref()
                    .ok_or_else(|| CodegenError::new("array schema must have an object 'items'"))?;
                Ok(format!(
                    "{}[]",
                    ts_type(items, &format!("{name_hint}Item"), ctx)?
                ))
            }
            Some("object") => Err(CodegenError::new(
                "inline object types aren't supported; use a $ref to a $def",
            )),
            other => Err(CodegenError::new(format!(
                "unsupported schema (need $ref, enum, or a known type), got type={other:?}"
            ))),
        }
    }
}

/// A string-union alias, e.g. `export type OptArgsMode = "fast" | "slow";`.
fn emit_enum_alias(name: &str, values: &[Value]) -> Result<String> {
    if values.is_empty() {
        return Err(CodegenError::new(format!(
            "enum {name:?} must have at least one value"
        )));
    }
    let mut variants: Vec<String> = Vec::new();
    for v in values {
        let s = v.as_str().ok_or_else(|| {
            CodegenError::new(format!("enum {name:?} values must all be strings"))
        })?;
        variants.push(str_lit(s));
    }
    Ok(format!("export type {name} = {};\n", variants.join(" | ")))
}

// --- shared TS naming helpers (reused by emit_ts_client) ----------------------

/// The TS module basename for the spec (its service `name`), sanitized like the Python module: each
/// non-`[A-Za-z0-9_]` char → `_`, a leading digit → `_`-prefixed. So `api.v1` → `api_v1`. Errors only
/// when nothing usable remains (e.g. an empty name).
pub(crate) fn ts_module(spec: &Spec) -> Result<String> {
    let mut out: String = spec
        .name
        .chars()
        .map(|c| {
            if c == '_' || c.is_ascii_alphanumeric() {
                c
            } else {
                '_'
            }
        })
        .collect();
    if out.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        out.insert(0, '_');
    }
    if out.is_empty() {
        return Err(CodegenError::new(format!(
            "spec name {:?} has no characters usable in a module identifier",
            spec.name
        )));
    }
    Ok(out)
}

/// The generated API-types module basename (`<module>_types`) the client imports from
/// (`import ... from "./<module>_types"`).
pub(crate) fn ts_types_module(module: &str) -> String {
    format!("{module}_types")
}

/// The generated client class name (`<Pascal>Client`), e.g. `sample` → `SampleClient`.
pub(crate) fn ts_client_class(spec: &Spec) -> String {
    format!("{}Client", pascal_case(&spec.name))
}
