//! Python-client emit — a Python extension module that is a **thin wrapper over the generated Rust
//! typed client**. For each `$defs` type it emits a `#[pyclass]` owning the Rust struct (a keyword
//! constructor and per-field getters, both via the `truenas-rpc-pyclient` serde boundary — no
//! per-shape code); for the service it emits a `#[pyclass] <Name>Client` that wraps the generated
//! `<Name>Client<JsonRpcClient>` and drives its typed async methods synchronously (the wire
//! (de)serialization stays in the Rust client). Subscriptions, filterable queries, and raw-fd
//! transfers are out of scope for this basic client (they need bespoke Python surfaces) and are
//! emitted as skip comments.
//!
//! The emitted code depends on `truenas-rpc-pyclient` + `pyo3` + the generated types & client modules
//! (NOT on this codegen crate). A consumer includes `types_gen.rs` + `client_gen.rs` +
//! `pyclient_gen.rs` and builds a `cdylib` with pyo3's `extension-module` feature.

use crate::error::{CodegenError, Result};
use crate::model::{Direction, SchemaNode, Spec};
use crate::naming::{pascal_case, rust_ident};
use crate::typemap::{ref_name, str_lit};

/// Generate the Python-client module: a typed `#[pyclass]` per `$defs` type + a client wrapping the
/// generated Rust typed client + the `#[pymodule]` init.
pub fn generate(spec: &Spec, origin: &str) -> Result<String> {
    let module = rust_ident(&spec.name).ok_or_else(|| {
        CodegenError::new(format!("spec name {:?} is not a valid Python module identifier", spec.name))
    })?;
    let client = format!("{}Client", pascal_case(&spec.name));

    let mut out = String::new();
    out.push_str(&header(origin));

    let mut classes: Vec<String> = Vec::new();
    for (name, schema) in spec.defs.iter() {
        out.push_str(&emit_type_class(name, schema)?);
        out.push('\n');
        classes.push(format!("Py{name}"));
    }

    out.push_str(&emit_client_class(spec, &client)?);
    out.push('\n');
    classes.push(format!("Py{client}"));

    out.push_str(&emit_module(&spec.name, &module, &classes));
    Ok(out)
}

fn header(origin: &str) -> String {
    format!(
        "// GENERATED by truenas-rpc-codegen from {origin} — DO NOT EDIT BY HAND.\n//\n// A PyO3 extension module: typed request/response classes + a client wrapping the generated Rust\n// typed client. Depends on `truenas-rpc-pyclient` + `pyo3` + the generated types & client.\n\n"
    )
}

/// A `#[pyclass]` owning the Rust struct: a `**kwargs` constructor + a getter per field (both through
/// the serde boundary, so nested `$ref` / enum / `Secret` / `Vec` / `Option` all work uniformly).
fn emit_type_class(name: &str, schema: &SchemaNode) -> Result<String> {
    if schema.ty.as_deref() != Some("object") {
        return Err(CodegenError::new(format!(
            "$defs.{name} must be a JSON object schema (got type={:?})",
            schema.ty
        )));
    }
    let mut s = String::new();
    s.push_str(&format!("#[pyo3::pyclass(name = {})]\n#[derive(Clone)]\n", str_lit(name)));
    s.push_str(&format!("pub struct Py{name} {{\n    inner: {name},\n}}\n\n"));
    s.push_str(&format!("#[pyo3::pymethods]\nimpl Py{name} {{\n"));
    s.push_str("    #[new]\n    #[pyo3(signature = (**kwargs))]\n");
    s.push_str("    fn new(py: pyo3::Python<'_>, kwargs: Option<pyo3::Bound<'_, pyo3::types::PyDict>>) -> pyo3::PyResult<Self> {\n");
    s.push_str("        let dict = match kwargs { Some(kwargs) => kwargs, None => pyo3::types::PyDict::new(py) };\n");
    s.push_str(&format!("        Ok(Py{name} {{ inner: truenas_rpc_pyclient::from_py(dict.as_any())? }})\n"));
    s.push_str("    }\n");
    for (pname, _pschema) in schema.properties.iter() {
        let field = rust_ident(pname).ok_or_else(|| {
            CodegenError::new(format!("$defs.{name} property {pname:?} is not a valid identifier"))
        })?;
        // The getter is `get_<field>` — pyo3 strips the `get_` prefix for the Python attribute name,
        // and the prefix keeps it from colliding with `new` / `__repr__` (a field could be named
        // either). The struct field is accessed by its raw-escaped identifier.
        s.push_str("    #[getter]\n");
        s.push_str(&format!(
            "    fn get_{pname}(&self, py: pyo3::Python<'_>) -> pyo3::PyResult<pyo3::PyObject> {{\n"
        ));
        s.push_str(&format!("        truenas_rpc_pyclient::to_py(py, &self.inner.{field})\n    }}\n"));
    }
    s.push_str(&format!("    fn __repr__(&self) -> String {{\n        format!(\"{name}({{:?}})\", self.inner)\n    }}\n"));
    s.push_str("}\n");
    Ok(s)
}

/// The `#[pyclass] <Name>Client`, wrapping the generated Rust `<Name>Client<JsonRpcClient>` and
/// driving its typed async methods on the shared runtime (GIL released).
fn emit_client_class(spec: &Spec, client: &str) -> Result<String> {
    let mut methods = String::new();
    for (wire, m) in spec.methods.iter() {
        // Out of scope for the basic Python client — each needs a bespoke Python surface (a filter
        // model, a notification stream, a blocking fd). Emitted as a skip comment, not silently.
        if m.direction() == Direction::ServerClient {
            methods.push_str(&format!("    // `{wire}`: server->client subscription — not in the basic Python client.\n"));
            continue;
        }
        if m.filterable {
            methods.push_str(&format!("    // `{wire}`: filterable query — not in the basic Python client.\n"));
            continue;
        }
        if m.transfer.is_some() {
            methods.push_str(&format!("    // `{wire}`: raw-fd transfer — not in the basic Python client.\n"));
            continue;
        }
        // plain / xdr / python: request -> result, delegating to the generated Rust typed method
        // (which already does the wire — including XDR by proc-id — and the typed decode).
        let params = ref_name_of(&m.params, "params")?;
        let result = ref_name_of(m.result.as_ref().ok_or_else(|| miss("result"))?, "result")?;
        let handler = &m.handler;
        methods.push_str(&format!("    /// Call `{wire}`.\n"));
        methods.push_str(&format!(
            "    fn {handler}(&self, py: pyo3::Python<'_>, request: &Py{params}) -> pyo3::PyResult<Py{result}> {{\n"
        ));
        // Same-module field access (the `inner` field is private but reachable here); the wrapped
        // Rust struct goes to the generated typed method, and its typed result is re-wrapped.
        methods.push_str("        let request = request.inner.clone();\n");
        methods.push_str("        let guard = self.inner.lock().expect(\"client mutex\");\n");
        methods.push_str("        let client = guard.as_ref().ok_or_else(|| truenas_rpc_pyclient::RpcError::new_err(\"client is closed\"))?;\n");
        methods.push_str(&format!(
            "        let out = py.allow_threads(|| truenas_rpc_pyclient::runtime().block_on(client.{handler}(request)));\n"
        ));
        methods.push_str(&format!(
            "        out.map(|inner| Py{result} {{ inner }}).map_err(truenas_rpc_pyclient::map_call_err)\n    }}\n"
        ));
    }

    let mut s = String::new();
    s.push_str(&format!("#[pyo3::pyclass(name = {})]\n", str_lit(client)));
    s.push_str(&format!(
        "pub struct Py{client} {{\n    inner: std::sync::Mutex<Option<{client}<truenas_rpc_client::JsonRpcClient>>>,\n}}\n\n"
    ));
    s.push_str(&format!("#[pyo3::pymethods]\nimpl Py{client} {{\n"));
    s.push_str(&format!("    /// Connect to `endpoint` and negotiate the `{}` protocol.\n", spec.name));
    s.push_str("    #[staticmethod]\n    #[pyo3(signature = (endpoint, config = None))]\n");
    s.push_str("    fn connect(py: pyo3::Python<'_>, endpoint: &truenas_rpc_pyclient::PyEndpoint, config: Option<&truenas_rpc_pyclient::PyClientConfig>) -> pyo3::PyResult<Self> {\n");
    s.push_str(&format!(
        "        let engine = truenas_rpc_pyclient::connect_blocking(py, endpoint.inner(), {}, config.map(|c| c.inner()))?;\n",
        str_lit(&spec.name)
    ));
    s.push_str(&format!(
        "        Ok(Py{client} {{ inner: std::sync::Mutex::new(Some({client}::new(engine))) }})\n    }}\n"
    ));
    s.push_str(&methods);
    s.push_str("    /// Disconnect (drops the connection — a hard close, no `$/sessionClose`).\n");
    s.push_str("    fn close(&self) -> pyo3::PyResult<()> {\n");
    s.push_str("        let _ = self.inner.lock().expect(\"client mutex\").take();\n");
    s.push_str("        Ok(())\n    }\n}\n");
    Ok(s)
}

fn emit_module(py_name: &str, module_fn: &str, classes: &[String]) -> String {
    let mut s = String::new();
    s.push_str("\n/// The generated Python extension module. Also callable directly (e.g. from a test)\n");
    s.push_str("/// to populate a `PyModule` with the classes.\n");
    s.push_str(&format!("#[pyo3::pymodule]\n#[pyo3(name = {})]\n", str_lit(py_name)));
    s.push_str(&format!(
        "pub fn {module_fn}(m: &pyo3::Bound<'_, pyo3::types::PyModule>) -> pyo3::PyResult<()> {{\n"
    ));
    // `add_class` lives on the `PyModuleMethods` extension trait; bring it into the fn scope (the
    // generated file is `include!`d, so it can't rely on the consumer's imports).
    s.push_str("    use pyo3::types::PyModuleMethods;\n");
    s.push_str("    truenas_rpc_pyclient::register_common(m)?;\n");
    for class in classes {
        s.push_str(&format!("    m.add_class::<{class}>()?;\n"));
    }
    s.push_str("    Ok(())\n}\n");
    s
}

fn ref_name_of(node: &SchemaNode, slot: &str) -> Result<String> {
    match &node.reference {
        Some(r) => ref_name(r),
        None => Err(CodegenError::new(format!("{slot} must be a $ref to a $def"))),
    }
}

fn miss(slot: &str) -> CodegenError {
    CodegenError::new(format!("missing '{slot}'"))
}
