//! Python client emit — a `<Pascal>Client` class over a **raw byte transport** (the `RawClient`
//! shim from `truenas-rpc-pyclient`, which exposes the Rust `truenas-rpc-client` engine as
//! `call(method, params_bytes) -> result_bytes`). Each plain `request -> result` method
//! msgspec-encodes the request, calls the transport, and msgspec-decodes the typed result.
//! Subscriptions / filterable / transfer methods aren't in this basic client (a comment marks them).

use std::collections::BTreeSet;

use crate::emit_py_structs::{
    client_class, finalize, is_plain_method, miss, py_module, ref_name_of, types_module,
};
use crate::error::Result;
use crate::model::Spec;
use crate::typemap::str_lit;

/// Generate the client module: a `<Pascal>Client` over a raw byte transport, one method per plain
/// `request -> result` RPC.
pub fn generate(spec: &Spec, origin: &str) -> Result<String> {
    let module = py_module(spec)?;
    let types_mod = types_module(&module);
    let class = client_class(spec);

    let mut methods = String::new();
    let mut used: BTreeSet<String> = BTreeSet::new();
    let mut decoders: Vec<(String, String)> = Vec::new(); // (wire, Result) in wire order
    for (wire, m) in spec.methods.iter() {
        if !is_plain_method(m) {
            methods.push_str(&skip_comment(wire, m));
            continue;
        }
        let params = ref_name_of(&m.params, "params")?;
        let result = ref_name_of(m.result.as_ref().ok_or_else(|| miss("result"))?, "result")?;
        used.insert(params.clone());
        used.insert(result.clone());
        decoders.push((wire.to_string(), result.clone()));
        methods.push_str(&emit_method(
            wire,
            &m.handler,
            &params,
            &result,
            m.summary.as_deref(),
        ));
    }

    let mut out = String::new();
    out.push_str(&header(origin));
    out.push_str(&imports(&types_mod, &used, !decoders.is_empty()));
    out.push_str("\n\n");
    // The reuse table (a shared encoder + a decoder per result type) — only when there are methods.
    if !decoders.is_empty() {
        out.push_str(&decoder_table(&decoders));
        out.push_str("\n\n");
    }
    out.push_str(&format!("class {class}:\n"));
    out.push_str(&format!(
        "    \"\"\"Typed msgspec client for the {} service — the connection object: connect with\n    `{class}.connect(endpoint)`, then call the protocol's methods on it.\"\"\"\n\n",
        str_lit(&spec.name)
    ));
    // Pinned protocol identity — selecting a version = instantiating the right client class.
    out.push_str(&format!("    PROTOCOL = {}\n", str_lit(&spec.name)));
    out.push_str(&format!("    VERSION = {}\n\n", str_lit(&spec.version)));
    out.push_str("    def __init__(self, raw: truenas_rpc_pyclient.RawClient) -> None:\n");
    out.push_str("        \"\"\"`raw` is the byte transport this client wraps (an internal detail; prefer `connect`).\"\"\"\n");
    out.push_str("        self._raw = raw\n");
    out.push_str("        self._negotiated: truenas_rpc_pyclient.Negotiated | None = None\n\n");
    out.push_str("    @classmethod\n");
    out.push_str(&format!(
        "    def connect(cls, endpoint: str) -> {class}:\n"
    ));
    out.push_str("        \"\"\"Connect over AF_UNIX at `endpoint` and `$/negotiate` this client's `PROTOCOL`.\"\"\"\n");
    out.push_str("        raw = truenas_rpc_pyclient.connect(endpoint, cls.PROTOCOL)\n");
    out.push_str("        obj = cls(raw)\n");
    out.push_str("        obj._negotiated = raw.negotiated()\n");
    out.push_str("        return obj\n\n");
    out.push_str("    @property\n");
    out.push_str("    def negotiated(self) -> truenas_rpc_pyclient.Negotiated | None:\n");
    out.push_str("        \"\"\"The `$/negotiate` result (`{'protocol', 'server', 'available'}`), or None for a BYO transport.\"\"\"\n");
    out.push_str("        return self._negotiated\n\n");
    out.push_str("    @property\n");
    out.push_str("    def available(self) -> list[str] | None:\n");
    out.push_str("        \"\"\"The protocol names the server offered at `$/negotiate` (discovery), or None for a BYO transport.\"\"\"\n");
    out.push_str(
        "        return None if self._negotiated is None else self._negotiated[\"available\"]\n",
    );
    if !methods.is_empty() {
        out.push('\n');
        out.push_str(&methods);
    }
    Ok(finalize(out))
}

fn header(origin: &str) -> String {
    format!(
        "# GENERATED by truenas-rpc-codegen from {origin} — DO NOT EDIT BY HAND.\n#\n# A typed msgspec client over a raw byte transport (`truenas-rpc-pyclient`'s `RawClient`): each\n# method encodes the request, calls the Rust engine, and decodes the typed result — reusing a\n# shared `Encoder` + a per-method `Decoder` built once at import (not rebuilt per call).\n\n"
    )
}

/// The import preamble: `MappingProxyType` (for the `_DECODERS` proxy, when there are methods),
/// `msgspec`, and the referenced API types (alphabetized) from the types module. Ends at the last
/// import line's newline (the caller adds the blank lines before the body).
fn imports(types_mod: &str, used: &BTreeSet<String>, has_decoders: bool) -> String {
    let mut out = String::from("from __future__ import annotations\n\n");
    if has_decoders {
        out.push_str("from types import MappingProxyType\nfrom typing import Any, cast\n\n");
    }
    out.push_str("import msgspec\nimport truenas_rpc_pyclient\n");
    if !used.is_empty() {
        let names: Vec<&str> = used.iter().map(String::as_str).collect();
        out.push_str(&format!("\nfrom {types_mod} import {}\n", names.join(", ")));
    }
    out
}

/// The module-level msgspec reuse table: one shared `Encoder` + a `Decoder` per method's result
/// type, built **once** and reused every call (msgspec's one-shot `json.decode`/`encode` rebuild
/// these each time). Keyed by wire name.
fn decoder_table(rows: &[(String, String)]) -> String {
    let mut entries = String::new();
    for (wire, result) in rows {
        entries.push_str(&format!(
            "    {}: msgspec.json.Decoder({result}),\n",
            str_lit(wire)
        ));
    }
    format!(
        "_ENCODER = msgspec.json.Encoder()\n_DECODERS: MappingProxyType[str, msgspec.json.Decoder[Any]] = MappingProxyType({{\n{entries}}})\n"
    )
}

/// One typed method: `_DECODERS["<wire>"].decode(self._raw.call("<wire>", _ENCODER.encode(request)))`
/// over the module-level reuse table. The Python method name is the handler symbol (a Python keyword
/// is `_`-suffixed).
fn emit_method(
    wire: &str,
    handler: &str,
    params: &str,
    result: &str,
    summary: Option<&str>,
) -> String {
    let ident = method_ident(handler);
    let w = str_lit(wire);
    let mut s = String::new();
    s.push_str(&format!(
        "    def {ident}(self, request: {params}) -> {result}:\n"
    ));
    if let Some(doc) = summary {
        s.push_str(&format!("        \"\"\"{doc}\"\"\"\n"));
    }
    s.push_str(&format!(
        "        return cast(\n            {result},\n            _DECODERS[{w}].decode(self._raw.call({w}, _ENCODER.encode(request))),\n        )\n\n"
    ));
    s
}

/// A one-line comment standing in for a method this basic client doesn't expose.
fn skip_comment(wire: &str, m: &crate::model::MethodSpec) -> String {
    let reason = if m.direction() == crate::model::Direction::ServerClient {
        "server->client subscription"
    } else if m.filterable {
        "filterable query"
    } else {
        "raw-fd transfer"
    };
    format!("    # {wire}: {reason} — not in the basic msgspec client.\n")
}

/// The handler symbol as a Python method name — `_`-suffixed if it collides with a Python keyword
/// (the json-idl already guarantees it's an identifier).
fn method_ident(handler: &str) -> String {
    if is_py_keyword(handler) {
        format!("{handler}_")
    } else {
        handler.to_string()
    }
}

/// Python 3 hard keywords (a handler named one of these can't be a bare method name).
fn is_py_keyword(s: &str) -> bool {
    matches!(
        s,
        "False"
            | "None"
            | "True"
            | "and"
            | "as"
            | "assert"
            | "async"
            | "await"
            | "break"
            | "class"
            | "continue"
            | "def"
            | "del"
            | "elif"
            | "else"
            | "except"
            | "finally"
            | "for"
            | "from"
            | "global"
            | "if"
            | "import"
            | "in"
            | "is"
            | "lambda"
            | "nonlocal"
            | "not"
            | "or"
            | "pass"
            | "raise"
            | "return"
            | "try"
            | "while"
            | "with"
            | "yield"
    )
}
