//! Server emit — typed `$def` structs, a `Handlers<S>`
//! trait (the consumer's binding point; a missing/mistyped method is a compile error), and
//! a `register()` that wires each method onto the core's builder. Fully-qualified paths
//! (`truenas_rpc::…`, `serde::…`) so the `include!`d output needs no `use`.

use std::collections::HashSet;

use serde_json::Value;

use crate::error::{CodegenError, Result};
use crate::model::{Direction, MethodSpec, SchemaNode, Spec};
use crate::naming::{pascal_case, rust_ident};
use crate::typemap::{ref_name, rust_type, str_lit, TypeCtx};

/// Generate the server module (structs + `Handlers` trait + `register()` + `PYTHON_METHODS`).
pub fn generate(spec: &Spec, origin: &str) -> Result<String> {
    let xdr = xdr_reachable(spec);
    let mut ctx = TypeCtx::default();
    let mut structs = String::new();
    let mut defaults = String::new();

    for (name, schema) in spec.defs.iter() {
        structs.push_str(&emit_struct(name, schema, xdr.contains(name), &mut ctx, &mut defaults)?);
        structs.push('\n');
    }

    let mut out = String::new();
    out.push_str(&header(origin));
    out.push_str(&structs);
    for def in ctx.enum_defs() {
        out.push_str(def);
        out.push_str("\n\n");
    }
    out.push_str(&defaults);
    if !defaults.is_empty() {
        out.push('\n');
    }
    out.push_str(&emit_handlers_trait(spec)?);
    out.push('\n');
    out.push_str(&emit_register(spec)?);
    out.push_str(&emit_audit(spec));
    out.push_str(&emit_python_table(spec));
    out.push_str(&emit_protocols(spec));
    Ok(out)
}

fn header(origin: &str) -> String {
    format!(
        "// GENERATED by truenas-rpc-codegen from {origin} — DO NOT EDIT BY HAND.\n//\n// Typed structs + a `Handlers` trait + `register()`. Implement `Handlers<S>` for your\n// server-state type and pass it to `register`; a missing/mistyped handler is a compile error.\n\n"
    )
}

/// The `$def` names reachable (transitively) from a method with `xdr:true`. Their optional
/// fields must serialize the optional discriminant (no `skip_serializing_if`).
fn xdr_reachable(spec: &Spec) -> HashSet<String> {
    let mut stack: Vec<String> = Vec::new();
    for (_, m) in spec.methods.iter() {
        if m.xdr {
            for node in [Some(&m.params), m.result.as_ref(), m.entry.as_ref()].into_iter().flatten() {
                push_ref(node, &mut stack);
            }
        }
    }
    let mut set = HashSet::new();
    while let Some(name) = stack.pop() {
        if set.insert(name.clone()) {
            // Names come from validated refs, so the def resolves; iterate its properties
            // (a missing name simply yields nothing).
            for (_, p) in spec.defs.get(&name).into_iter().flat_map(|d| d.properties.iter()) {
                collect_refs(p, &mut stack);
            }
        }
    }
    set
}

fn push_ref(node: &SchemaNode, stack: &mut Vec<String>) {
    if let Some(r) = &node.reference {
        if let Ok(n) = ref_name(r) {
            stack.push(n);
        }
    }
}

fn collect_refs(node: &SchemaNode, stack: &mut Vec<String>) {
    // A property is a $ref, a scalar, or an array (a nested object is rejected at emit), so
    // refs come only from the node itself or its array element type.
    push_ref(node, stack);
    if let Some(items) = &node.items {
        collect_refs(items, stack);
    }
}

fn emit_struct(
    name: &str,
    schema: &SchemaNode,
    xdr: bool,
    ctx: &mut TypeCtx,
    defaults: &mut String,
) -> Result<String> {
    if schema.ty.as_deref() != Some("object") {
        return Err(CodegenError::new(format!(
            "$defs.{name} must be a JSON object schema (got type={:?})",
            schema.ty
        )));
    }
    let mut fields = String::new();
    for (pname, pschema) in schema.properties.iter() {
        let ident = rust_ident(pname).ok_or_else(|| {
            CodegenError::new(format!("$defs.{name} property {pname:?} is not a valid identifier"))
        })?;
        let hint = format!("{name}{}", pascal_case(pname));
        let base = rust_type(pschema, &hint, ctx)?;
        let required = schema.required.iter().any(|r| r == pname);

        if let Some(default) = &pschema.default {
            let (attr, default_fn) = render_default(name, pname, pschema, &base, default)?;
            fields.push_str(&attr);
            fields.push_str(&format!("    pub {ident}: {base},\n"));
            if let Some(f) = default_fn {
                defaults.push_str(&f);
            }
        } else if required {
            fields.push_str(&format!("    pub {ident}: {base},\n"));
        } else if xdr {
            // XDR-reachable: keep the optional discriminant on the wire (no skip).
            fields.push_str("    #[serde(default)]\n");
            fields.push_str(&format!("    pub {ident}: Option<{base}>,\n"));
        } else {
            fields.push_str("    #[serde(default, skip_serializing_if = \"Option::is_none\")]\n");
            fields.push_str(&format!("    pub {ident}: Option<{base}>,\n"));
        }
    }
    let body = if fields.is_empty() { String::new() } else { format!("\n{fields}") };
    Ok(format!(
        "#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]\npub struct {name} {{{body}}}\n"
    ))
}

/// Returns the serde attr line and an optional module-level default fn.
fn render_default(
    struct_name: &str,
    field: &str,
    pschema: &SchemaNode,
    base: &str,
    default: &Value,
) -> Result<(String, Option<String>)> {
    // (is_type_default, the Rust default expression)
    let (is_type_default, expr) = if pschema.enum_values.is_some() {
        let s = default
            .as_str()
            .ok_or_else(|| CodegenError::new("enum default must be a string"))?;
        (false, format!("{base}::{}", pascal_case(s)))
    } else {
        match pschema.ty.as_deref() {
            Some("string") => {
                let s = default.as_str().ok_or_else(|| CodegenError::new("string default must be a string"))?;
                (s.is_empty(), format!("{}.to_string()", str_lit(s)))
            }
            Some("integer") => {
                let n = default.as_i64().ok_or_else(|| CodegenError::new("integer default must be an integer"))?;
                (n == 0, format!("{n}i64"))
            }
            // Always emit a fn for floats (avoids a float-equality comparison here).
            Some("number") => {
                let f = default.as_f64().ok_or_else(|| CodegenError::new("number default must be a number"))?;
                (false, format!("{f:?}f64"))
            }
            Some("boolean") => {
                let b = default.as_bool().ok_or_else(|| CodegenError::new("boolean default must be a boolean"))?;
                (!b, format!("{b}"))
            }
            Some("array") => {
                let empty = default.as_array().is_some_and(|a| a.is_empty());
                if !empty {
                    return Err(CodegenError::new("only an empty-array default ([]) is supported"));
                }
                (true, "Vec::new()".to_string())
            }
            other => {
                return Err(CodegenError::new(format!("unsupported default for type {other:?}")))
            }
        }
    };
    if is_type_default {
        Ok(("    #[serde(default)]\n".to_string(), None))
    } else {
        let fn_name = format!("default_{}_{field}", struct_name.to_lowercase());
        let attr = format!("    #[serde(default = {})]\n", str_lit(&fn_name));
        let def = format!("fn {fn_name}() -> {base} {{ {expr} }}\n");
        Ok((attr, Some(def)))
    }
}

/// Kinds of method (drives the trait method + register line).
enum Kind {
    Plain,
    Async,
    Filterable,
    Subscription,
    Python,
}

fn kind_of(m: &MethodSpec) -> Kind {
    if m.python {
        Kind::Python
    } else if m.direction() == Direction::ServerClient {
        Kind::Subscription
    } else if m.filterable {
        Kind::Filterable
    } else if m.is_async {
        Kind::Async
    } else {
        Kind::Plain
    }
}

fn emit_handlers_trait(spec: &Spec) -> Result<String> {
    let mut methods = String::new();
    for (_, m) in spec.methods.iter() {
        let params = ref_name_of(&m.params, "params")?;
        match kind_of(m) {
            Kind::Plain => {
                let result = ref_name_of(m.result.as_ref().ok_or_else(|| miss(m, "result"))?, "result")?;
                methods.push_str(&format!(
                    "    /// Handler for `{}`.\n    fn {}(&self, request: {params}, cx: &truenas_rpc::RequestCtx<S>) -> Result<{result}, truenas_rpc::JsonRpcError>;\n",
                    wire_doc(spec, m), m.handler
                ));
            }
            Kind::Async => {
                let result = ref_name_of(m.result.as_ref().ok_or_else(|| miss(m, "result"))?, "result")?;
                // RPITIT (`-> impl Future + Send`, stable since 1.75) — no `async-trait` dep on the
                // generated code. Implement it with `async fn {handler}(..)`. `cx` is by value (the
                // future is awaited on the runtime, not borrowing the dispatch frame).
                methods.push_str(&format!(
                    "    /// Async handler for `{}`.\n    fn {}(&self, request: {params}, cx: truenas_rpc::RequestCtx<S>) -> impl ::core::future::Future<Output = Result<{result}, truenas_rpc::JsonRpcError>> + Send;\n",
                    wire_doc(spec, m), m.handler
                ));
            }
            Kind::Filterable => {
                let entry = ref_name_of(
                    m.entry.as_ref().expect("filterable entry present (guaranteed by validate)"),
                    "entry",
                )?;
                methods.push_str(&format!(
                    "    /// Filterable handler for `{}`.\n    fn {}(&self, request: {params}, cx: &truenas_rpc::RequestCtx<S>, filters: &truenas_rpc::CompiledFilters, options: &truenas_rpc::CompiledOptions) -> Result<truenas_rpc::Filtered<{entry}>, truenas_rpc::JsonRpcError>;\n",
                    wire_doc(spec, m), m.handler
                ));
            }
            Kind::Subscription | Kind::Python => {} // no trait method
        }
    }
    Ok(format!(
        "/// Implement for your server-state type `S`: one method per request/filterable RPC.\npub trait Handlers<S>: Send + Sync {{\n{methods}}}\n"
    ))
}

fn emit_register(spec: &Spec) -> Result<String> {
    let mut body = String::new();
    let mut uses_handlers = false;
    for (wire, m) in spec.methods.iter() {
        let def = method_def_expr(spec, wire, m);
        match kind_of(m) {
            Kind::Plain => {
                uses_handlers = true;
                let params = ref_name_of(&m.params, "params")?;
                body.push_str(&format!(
                    "    let h = handlers.clone();\n    let builder = builder.method(truenas_rpc::RpcMethod::new({def}, move |request: {params}, cx: &truenas_rpc::RequestCtx<S>| h.{}(request, cx)))?;\n",
                    m.handler
                ));
            }
            Kind::Async => {
                uses_handlers = true;
                let params = ref_name_of(&m.params, "params")?;
                // Clone the `Arc<H>` into each invocation's future so it owns its handle (a `Fn`
                // closure can't move its capture), and await the handler inline on the runtime.
                body.push_str(&format!(
                    "    let h = handlers.clone();\n    let builder = builder.async_method(truenas_rpc::AsyncRpcMethod::new({def}, move |request: {params}, cx: truenas_rpc::RequestCtx<S>| {{\n        let h = h.clone();\n        async move {{ h.{}(request, cx).await }}\n    }}))?;\n",
                    m.handler
                ));
            }
            Kind::Filterable => {
                uses_handlers = true;
                let params = ref_name_of(&m.params, "params")?;
                let entry = ref_name_of(
                    m.entry.as_ref().expect("filterable entry present (guaranteed by validate)"),
                    "entry",
                )?;
                body.push_str(&format!(
                    "    let h = handlers.clone();\n    let builder = builder.filterable(truenas_rpc::FilterableRpcMethod::<{params}, {entry}, _>::new({def}, move |request: {params}, cx: &truenas_rpc::RequestCtx<S>, filters: &truenas_rpc::CompiledFilters, options: &truenas_rpc::CompiledOptions| h.{}(request, cx, filters, options)))?;\n",
                    m.handler
                ));
            }
            Kind::Subscription => {
                let params = ref_name_of(&m.params, "params")?;
                let notifies = ref_name_of(m.notifies.as_ref().ok_or_else(|| miss(m, "notifies"))?, "notifies")?;
                body.push_str(&format!(
                    "    let builder = builder.subscription(truenas_rpc::SubscriptionDef::<{params}, {notifies}>::new({def}))?;\n"
                ));
            }
            Kind::Python => {
                body.push_str(&format!("    let builder = builder.python_method({def})?;\n"));
            }
        }
    }
    let prelude = if uses_handlers { "" } else { "    let _ = &handlers;\n" };
    // On by default: install the spec-configured audit sink (empty identity — override via
    // `make_audit_sink`). Emitted only when auditing is enabled (so a disabled spec needs no
    // `truenas-audit` dependency).
    let audit_install = if spec.resolved_audit().is_some() {
        "    let builder = builder.audit_sink(make_audit_sink::<S, _>(|_session: &truenas_rpc::Session<S>| truenas_audit::AuditPrincipal::default()));\n"
    } else {
        ""
    };
    Ok(format!(
        "/// Register every spec method onto `builder`, binding each to `handlers.<handler>`.\npub fn register<S, H>(\n    builder: truenas_rpc::JsonRpcProtocolBuilder<S>,\n    handlers: std::sync::Arc<H>,\n) -> truenas_rpc::BuildResult<truenas_rpc::JsonRpcProtocolBuilder<S>>\nwhere\n    S: Send + Sync + 'static,\n    H: Handlers<S> + 'static,\n{{\n{prelude}{body}{audit_install}    Ok(builder)\n}}\n"
    ))
}

/// Emit the `make_audit_sink` helper — only when auditing is enabled. It carries the spec's
/// configured `service` + `queueBound`; the consumer supplies the identity extractor.
fn emit_audit(spec: &Spec) -> String {
    let Some(audit) = spec.resolved_audit() else { return String::new() };
    let queue = match audit.queue_bound {
        Some(n) => format!(".queue_bound({n}usize)"),
        None => String::new(),
    };
    format!(
        "\n/// Build the spec-configured Linux kernel-audit sink with your identity extractor.\n/// `register` installs one with an empty extractor by default; pass an extractor that reads your\n/// session state and re-install via `.audit_sink(..)` to attribute records (`acct=`, uid, origin).\npub fn make_audit_sink<S, F>(identity: F) -> truenas_audit::LinuxAuditSink<S>\nwhere\n    S: Send + Sync + 'static,\n    F: Fn(&truenas_rpc::Session<S>) -> truenas_audit::AuditPrincipal + Send + Sync + 'static,\n{{\n    truenas_audit::LinuxAuditSink::<S>::builder({service}){queue}.identity(identity).build()\n}}\n",
        service = str_lit(&audit.service),
    )
}

/// The declared wire protocols as a const, plus — when `onc-rpc` is declared — the default ONC RPC
/// program/version so a consumer can wire `OncRpc::protocol(name).at(ONC_PROGRAM, ONC_VERSION)`
/// without magic numbers. The program/version are generic RFC 5531 user-range defaults (a server-wiring
/// concern, kept out of the IDL); override them per listener.
fn emit_protocols(spec: &Spec) -> String {
    let lits: Vec<String> = spec.protocols.iter().map(|p| str_lit(p)).collect();
    let mut out = format!(
        "\n/// The wire protocols this service is served over (from the json-idl `protocols`).\npub const PROTOCOLS: &[&str] = &[{}];\n",
        lits.join(", ")
    );
    if spec.protocols.iter().any(|p| p == "onc-rpc") {
        out.push_str(
            "\n/// Default ONC RPC program/version this service answers to (override per listener).\npub const ONC_PROGRAM: u32 = 0x2000_0001;\npub const ONC_VERSION: u32 = 1;\n",
        );
    }
    out
}

fn emit_python_table(spec: &Spec) -> String {
    let names: Vec<String> = spec
        .methods
        .iter()
        .filter(|(_, m)| m.python)
        .map(|(w, _)| str_lit(w))
        .collect();
    if names.is_empty() {
        String::new()
    } else {
        format!(
            "\n/// The `python:true` methods (bodies run via the PyO3 bridge, not `Handlers`).\npub const PYTHON_METHODS: &[&str] = &[{}];\n",
            names.join(", ")
        )
    }
}

fn method_def_expr(spec: &Spec, wire: &str, m: &MethodSpec) -> String {
    let mut s = format!("truenas_rpc::MethodDef::new({})", str_lit(wire));
    if let Some(doc) = &m.summary {
        s.push_str(&format!(".doc({})", str_lit(doc)));
    }
    if m.pre_auth {
        s.push_str(".pre_auth()");
    }
    if let Some(msg) = &m.audit_message {
        s.push_str(&format!(".audit_message({})", str_lit(msg)));
    } else if m.audit {
        s.push_str(".audit()");
    }
    if m.cancellable {
        s.push_str(".cancellable()");
    }
    if !m.roles.is_empty() {
        let roles: Vec<String> = m.roles.iter().map(|r| str_lit(r)).collect();
        s.push_str(&format!(".roles([{}])", roles.join(", ")));
    }
    let secrets = secret_param_fields(spec, m);
    if !secrets.is_empty() {
        let lits: Vec<String> = secrets.iter().map(|f| str_lit(f)).collect();
        s.push_str(&format!(".secret_fields([{}])", lits.join(", ")));
    }
    if m.xdr {
        if let Some(id) = m.xdr_id {
            s.push_str(&format!(".xdr({id}u32)"));
        }
    }
    if let Some(cap) = reply_capacity(spec, m) {
        s.push_str(&format!(".reply_capacity({cap})"));
    }
    s
}

/// ~ the JSON-RPC reply envelope skeleton `{"jsonrpc":"2.0","result":<>,"id":"<36-char uuid>"}`.
const REPLY_ENVELOPE_BYTES: usize = 72;

/// A generous estimate of the JSON bytes a value of `node`'s shape serializes to — used only to
/// pre-size the reply buffer (`MethodDef::reply_capacity`). Over-estimating reserves a few extra
/// bytes once; under-estimating costs one realloc. Fixed-shape types (integers/bools/fixed objects)
/// land near-exact; variable ones (strings/arrays) get a typical-small allowance. `$ref`s resolve
/// through `spec.defs`, recursion-guarded.
fn json_value_bytes(node: &SchemaNode, spec: &Spec, depth: usize) -> usize {
    if depth > 8 {
        return 16;
    }
    if let Some(r) = &node.reference {
        if let Ok(name) = ref_name(r) {
            if let Some(d) = spec.defs.get(&name) {
                return json_value_bytes(d, spec, depth + 1);
            }
        }
        return 16;
    }
    match node.ty.as_deref() {
        Some("integer") => 20, // i64 text + sign
        Some("number") => 24,
        Some("boolean") => 5,
        Some("string") => 24, // "<short string>"; content variable
        Some("array") => 2 + node.items.as_ref().map_or(16, |it| json_value_bytes(it, spec, depth + 1)),
        Some("object") => {
            2 + node
                .properties
                .iter()
                .map(|(name, p)| name.len() + 4 + json_value_bytes(p, spec, depth + 1))
                .sum::<usize>()
        }
        _ => 16, // enum / unknown
    }
}

/// The per-method reply-buffer reservation: the JSON-RPC envelope plus its result (or, for a
/// filterable method, one `entry`). `None` for methods with no result/entry (subscription, python,
/// transfer), which keep the default unsized buffer.
fn reply_capacity(spec: &Spec, m: &MethodSpec) -> Option<usize> {
    let node = m.result.as_ref().or(m.entry.as_ref())?;
    Some(REPLY_ENVELOPE_BYTES + json_value_bytes(node, spec, 0))
}

/// The wire-names of the secret properties in a method's params `$def` (fed to
/// `MethodDef::secret_fields` for the core's name-based audit redaction).
fn secret_param_fields(spec: &Spec, m: &MethodSpec) -> Vec<String> {
    let Some(reference) = &m.params.reference else { return Vec::new() };
    let Ok(name) = ref_name(reference) else { return Vec::new() };
    let Some(def) = spec.defs.get(&name) else { return Vec::new() };
    def.properties.iter().filter(|(_, p)| p.secret).map(|(k, _)| k.to_string()).collect()
}

fn ref_name_of(node: &SchemaNode, slot: &str) -> Result<String> {
    match &node.reference {
        Some(r) => ref_name(r),
        None => Err(CodegenError::new(format!("{slot} must be a $ref to a $def"))),
    }
}

fn miss(m: &MethodSpec, slot: &str) -> CodegenError {
    CodegenError::new(format!("method with handler {:?} is missing '{slot}'", m.handler))
}

fn wire_doc(_spec: &Spec, m: &MethodSpec) -> String {
    m.handler.clone()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn spec(defs: serde_json::Value) -> Spec {
        serde_json::from_value(serde_json::json!({
            "name": "t",
            "version": "1",
            "$defs": defs,
            "methods": {},
        }))
        .expect("minimal spec deserializes")
    }

    /// The `json_value_bytes` arms the golden specs don't reach: a self-referential `$ref` (the
    /// recursion guard), an unresolved `$ref`, and a typeless/unknown node — each returns the
    /// catch-all 16-byte default.
    #[test]
    fn reply_capacity_size_walker_guards_and_defaults() {
        let s = spec(serde_json::json!({ "A": { "$ref": "#/$defs/A" } }));

        let self_ref = SchemaNode { reference: Some("#/$defs/A".to_string()), ..Default::default() };
        assert_eq!(json_value_bytes(&self_ref, &s, 0), 16, "recursion guard (depth > 8)");

        let dangling = SchemaNode { reference: Some("#/$defs/Missing".to_string()), ..Default::default() };
        assert_eq!(json_value_bytes(&dangling, &s, 0), 16, "unresolved $ref (name resolves, def absent)");

        let malformed = SchemaNode { reference: Some("#/components/Foo".to_string()), ..Default::default() };
        assert_eq!(json_value_bytes(&malformed, &s, 0), 16, "malformed $ref (ref_name errors)");

        assert_eq!(json_value_bytes(&SchemaNode::default(), &s, 0), 16, "unknown / typeless node");
    }
}
