//! Types emit — the `$defs` structs (+ generated enums + serde default fns), factored out so **both**
//! the server (`Handlers` / `register`) and the typed client reference **one** set of types. A
//! consumer includes `types_gen.rs` alongside `server_gen.rs` and/or `client_gen.rs`; a standalone
//! client (no server bindings) needs only `types_gen.rs` + `client_gen.rs`.

use std::collections::HashSet;

use serde_json::Value;

use crate::error::{CodegenError, Result};
use crate::model::{SchemaNode, Spec};
use crate::naming::{pascal_case, rust_ident};
use crate::typemap::{ref_name, rust_type, str_lit, TypeCtx};

/// Generate the shared types module: the `$defs` structs, any generated enums, and serde default fns.
pub fn generate(spec: &Spec, origin: &str) -> Result<String> {
    let xdr = xdr_reachable(spec);
    let mut ctx = TypeCtx::default();
    let mut structs = String::new();
    let mut defaults = String::new();

    for (name, schema) in spec.defs.iter() {
        structs.push_str(&emit_struct(name, schema, xdr.contains(name), &mut ctx, &mut defaults)?);
        structs.push('\n');
    }

    let mut out = String::new();
    out.push_str(&header(origin));
    out.push_str(&structs);
    for def in ctx.enum_defs() {
        out.push_str(def);
        out.push_str("\n\n");
    }
    out.push_str(&defaults);
    if !defaults.is_empty() {
        out.push('\n');
    }
    Ok(out)
}

fn header(origin: &str) -> String {
    format!(
        "// GENERATED by truenas-rpc-codegen from {origin} — DO NOT EDIT BY HAND.\n//\n// The shared `$defs` types for the generated server (`Handlers`/`register`) and the typed client.\n\n"
    )
}

/// The `$def` names reachable (transitively) from a method with `xdr:true`. Their optional
/// fields must serialize the optional discriminant (no `skip_serializing_if`).
fn xdr_reachable(spec: &Spec) -> HashSet<String> {
    let mut stack: Vec<String> = Vec::new();
    for (_, m) in spec.methods.iter() {
        if m.xdr {
            for node in [Some(&m.params), m.result.as_ref(), m.entry.as_ref()].into_iter().flatten() {
                push_ref(node, &mut stack);
            }
        }
    }
    let mut set = HashSet::new();
    while let Some(name) = stack.pop() {
        if set.insert(name.clone()) {
            // Names come from validated refs, so the def resolves; iterate its properties
            // (a missing name simply yields nothing).
            for (_, p) in spec.defs.get(&name).into_iter().flat_map(|d| d.properties.iter()) {
                collect_refs(p, &mut stack);
            }
        }
    }
    set
}

fn push_ref(node: &SchemaNode, stack: &mut Vec<String>) {
    if let Some(r) = &node.reference {
        if let Ok(n) = ref_name(r) {
            stack.push(n);
        }
    }
}

fn collect_refs(node: &SchemaNode, stack: &mut Vec<String>) {
    // A property is a $ref, a scalar, or an array (a nested object is rejected at emit), so
    // refs come only from the node itself or its array element type.
    push_ref(node, stack);
    if let Some(items) = &node.items {
        collect_refs(items, stack);
    }
}

fn emit_struct(
    name: &str,
    schema: &SchemaNode,
    xdr: bool,
    ctx: &mut TypeCtx,
    defaults: &mut String,
) -> Result<String> {
    if schema.ty.as_deref() != Some("object") {
        return Err(CodegenError::new(format!(
            "$defs.{name} must be a JSON object schema (got type={:?})",
            schema.ty
        )));
    }
    let mut fields = String::new();
    for (pname, pschema) in schema.properties.iter() {
        let ident = rust_ident(pname).ok_or_else(|| {
            CodegenError::new(format!("$defs.{name} property {pname:?} is not a valid identifier"))
        })?;
        let hint = format!("{name}{}", pascal_case(pname));
        let base = rust_type(pschema, &hint, ctx)?;
        let required = schema.required.iter().any(|r| r == pname);

        if let Some(default) = &pschema.default {
            let (attr, default_fn) = render_default(name, pname, pschema, &base, default)?;
            fields.push_str(&attr);
            fields.push_str(&format!("    pub {ident}: {base},\n"));
            if let Some(f) = default_fn {
                defaults.push_str(&f);
            }
        } else if required {
            fields.push_str(&format!("    pub {ident}: {base},\n"));
        } else if xdr {
            // XDR-reachable: keep the optional discriminant on the wire (no skip).
            fields.push_str("    #[serde(default)]\n");
            fields.push_str(&format!("    pub {ident}: Option<{base}>,\n"));
        } else {
            fields.push_str("    #[serde(default, skip_serializing_if = \"Option::is_none\")]\n");
            fields.push_str(&format!("    pub {ident}: Option<{base}>,\n"));
        }
    }
    let body = if fields.is_empty() { String::new() } else { format!("\n{fields}") };
    Ok(format!(
        "#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]\npub struct {name} {{{body}}}\n"
    ))
}

/// Returns the serde attr line and an optional module-level default fn.
fn render_default(
    struct_name: &str,
    field: &str,
    pschema: &SchemaNode,
    base: &str,
    default: &Value,
) -> Result<(String, Option<String>)> {
    // (is_type_default, the Rust default expression)
    let (is_type_default, expr) = if pschema.enum_values.is_some() {
        let s = default
            .as_str()
            .ok_or_else(|| CodegenError::new("enum default must be a string"))?;
        (false, format!("{base}::{}", pascal_case(s)))
    } else {
        match pschema.ty.as_deref() {
            Some("string") => {
                let s = default.as_str().ok_or_else(|| CodegenError::new("string default must be a string"))?;
                (s.is_empty(), format!("{}.to_string()", str_lit(s)))
            }
            Some("integer") => {
                let n = default.as_i64().ok_or_else(|| CodegenError::new("integer default must be an integer"))?;
                (n == 0, format!("{n}i64"))
            }
            // Always emit a fn for floats (avoids a float-equality comparison here).
            Some("number") => {
                let f = default.as_f64().ok_or_else(|| CodegenError::new("number default must be a number"))?;
                (false, format!("{f:?}f64"))
            }
            Some("boolean") => {
                let b = default.as_bool().ok_or_else(|| CodegenError::new("boolean default must be a boolean"))?;
                (!b, format!("{b}"))
            }
            Some("array") => {
                let empty = default.as_array().is_some_and(|a| a.is_empty());
                if !empty {
                    return Err(CodegenError::new("only an empty-array default ([]) is supported"));
                }
                (true, "Vec::new()".to_string())
            }
            other => {
                return Err(CodegenError::new(format!("unsupported default for type {other:?}")))
            }
        }
    };
    if is_type_default {
        Ok(("    #[serde(default)]\n".to_string(), None))
    } else {
        let fn_name = format!("default_{}_{field}", struct_name.to_lowercase());
        let attr = format!("    #[serde(default = {})]\n", str_lit(&fn_name));
        let def = format!("fn {fn_name}() -> {base} {{ {expr} }}\n");
        Ok((attr, Some(def)))
    }
}
