# Generated by truenas_pyjsonrpc codegen — do not edit by hand.
# Protocol: 'truenas'
from __future__ import annotations

from collections.abc import Callable
from typing import Any

from truenas_pyjsonrpc import FileTransfer
from truenas_pyjsonrpc_client import BaseClient, TCPConfig, UnixConfig, WebSocketConfig

from api import FileDownloadArgs, FileDownloadResult, NoParams, PoolCreateArgs, PoolCreateResult, PoolEvent


class TruenasClient(BaseClient):
    """Typed client for the 'truenas' protocol (generated)."""

    def __init__(self, *, unix_config: UnixConfig | None = None,
                 tcp_config: TCPConfig | None = None,
                 websocket_config: WebSocketConfig | None = None,
                 name: str | None = None,
                 on_notification: Callable[[str, Any], None] | None = None,
                 connect_timeout: float = 10.0,
                 call_timeout: float | None = 30.0) -> None:
        super().__init__('truenas', unix_config=unix_config,
                         tcp_config=tcp_config,
                         websocket_config=websocket_config,
                         name=name, on_notification=on_notification,
                         connect_timeout=connect_timeout,
                         call_timeout=call_timeout)

    TOPICS: dict[str, type] = {'pool.events': PoolEvent}

    def file_download(self, request: FileDownloadArgs, *, callback: Callable[[FileTransfer], object]) -> FileDownloadResult:
        """Download (raw-fd transfer); ``callback(file_transfer)`` gets exclusive access to the connection's fd (``file_transfer.fileno()``) for the stream."""
        return self._typed_transfer('file.download', request, FileDownloadResult, callback)

    def pool_create(self, request: PoolCreateArgs, *, progress: Callable[[Any], None] | None = None) -> PoolCreateResult:
        return self._typed_call('pool.create', request, PoolCreateResult, progress=progress)

    def subscribe_pool_events(self, request: NoParams, *, callback: Callable[[PoolEvent], None] | None = None) -> str:
        """Subscribe to the 'pool.events' topic; returns the subscription id.

        ``callback`` (invoked on the backchannel thread) receives each published
        PoolEvent. Without it, messages fall through to on_notification."""
        return self._subscribe('pool.events', request, callback=callback, notifies=PoolEvent)
