//! GENERATED by api-specs/gen.py from api-specs/sample.json — DO NOT EDIT BY HAND.
//! Regenerate: python3 api-specs/gen.py api-specs/sample.json --out <this file>
//!
//! Typed structs + a `register()` table for the spec's methods. Handlers are NOT generated:
//! pass a `*Handlers` whose `pub fn`s match each method's `handler` symbol; `register` binds
//! them via the engine's `b.method` primitive (a missing/mistyped handler is a compile error).

const trpc = @import("truenas_jsonrpc");
pub const LoginArgs = struct {
    user: []const u8,
    password: trpc.Secret([]const u8),
};

pub const LoginResult = struct {
    token: trpc.Secret([]const u8),
    ok: bool,
};

pub const PingArgs = struct {};

pub const PingResult = struct {
    pong: bool,
};

pub const CrashArgs = struct {};

pub const Inner = struct {
    x: i64,
};

pub const Demo = struct {
    name: []const u8,
    count: i64 = 0,
    ratio: f64 = 1.5,
    note: ?[]const u8 = null,
    tags: ?[]const []const u8 = null,
    color: enum { red, green, blue },
    inner: Inner,
    api_key: trpc.Secret([]const u8),
};

/// Register every spec method onto `b`, binding each to `handlers.<handler>`.
pub fn register(b: anytype, handlers: anytype) !void {
    const H = @TypeOf(handlers.*);
    try b.method("login", handlers, H.login, .{ .audit = true, .audit_message = "user login" });
    try b.method("ping", handlers, H.ping, .{});
    try b.method("crash", handlers, H.crash, .{ .audit = true, .audit_message = "crash op" });
}
