// GENERATED by truenas-rpc-codegen from tests/fixtures/sample — DO NOT EDIT BY HAND.
//
// Typed structs + a `Handlers` trait + `register()`. Implement `Handlers<S>` for your
// server-state type and pass it to `register`; a missing/mistyped handler is a compile error.

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct LoginArgs {
    pub user: String,
    pub password: truenas_rpc::Secret<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct LoginResult {
    pub token: truenas_rpc::Secret<String>,
    pub ok: bool,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct PingArgs {}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct PingResult {
    pub pong: bool,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct CrashArgs {}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Inner {
    pub x: i64,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Demo {
    pub name: String,
    #[serde(default)]
    pub count: i64,
    #[serde(default = "default_demo_ratio")]
    pub ratio: f64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    pub color: DemoColor,
    pub inner: Inner,
    pub api_key: truenas_rpc::Secret<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct QueryArgs {}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Entry {
    pub id: i64,
    pub name: String,
    pub ratio: f64,
    pub active: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct XferArgs {
    pub n: i64,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct DownloadReady {
    pub size: i64,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct DownloadDone {
    pub sent: i64,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct UploadDone {
    pub received: i64,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum DemoColor {
    #[serde(rename = "red")]
    Red,
    #[serde(rename = "green")]
    Green,
    #[serde(rename = "blue")]
    Blue,
}

fn default_demo_ratio() -> f64 { 1.5f64 }

/// Implement for your server-state type `S`: one method per request/filterable RPC.
pub trait Handlers<S>: Send + Sync {
    /// Handler for `login`.
    fn login(&self, request: LoginArgs, cx: &truenas_rpc::RequestCtx<S>) -> Result<LoginResult, truenas_rpc::JsonRpcError>;
    /// Handler for `ping`.
    fn ping(&self, request: PingArgs, cx: &truenas_rpc::RequestCtx<S>) -> Result<PingResult, truenas_rpc::JsonRpcError>;
    /// Handler for `crash`.
    fn crash(&self, request: CrashArgs, cx: &truenas_rpc::RequestCtx<S>) -> Result<PingResult, truenas_rpc::JsonRpcError>;
    /// Filterable handler for `query`.
    fn query(&self, request: QueryArgs, cx: &truenas_rpc::RequestCtx<S>, filters: &truenas_rpc::CompiledFilters, options: &truenas_rpc::CompiledOptions) -> Result<truenas_rpc::Filtered<Entry>, truenas_rpc::JsonRpcError>;
    /// Transfer `negotiate` for `download` — validate the request, return the `$/transferReady` interim.
    fn download_ready(&self, request: &XferArgs, cx: &truenas_rpc::RequestCtx<S>) -> Result<DownloadReady, truenas_rpc::JsonRpcError>;
    /// Transfer handler for `download` — lent the connection's raw fd, produce the final result.
    fn download(&self, request: XferArgs, ft: &dyn truenas_rpc::FileTransfer) -> Result<DownloadDone, truenas_rpc::JsonRpcError>;
    /// Transfer `negotiate` for `upload` — validate the request, return the `$/transferReady` interim.
    fn upload_ready(&self, request: &XferArgs, cx: &truenas_rpc::RequestCtx<S>) -> Result<serde_json::Value, truenas_rpc::JsonRpcError>;
    /// Transfer handler for `upload` — lent the connection's raw fd, produce the final result.
    fn upload(&self, request: XferArgs, ft: &dyn truenas_rpc::FileTransfer) -> Result<UploadDone, truenas_rpc::JsonRpcError>;
}

/// Register every spec method onto `builder`, binding each to `handlers.<handler>`.
pub fn register<S, H>(
    builder: truenas_rpc::JsonRpcProtocolBuilder<S>,
    handlers: std::sync::Arc<H>,
) -> truenas_rpc::BuildResult<truenas_rpc::JsonRpcProtocolBuilder<S>>
where
    S: Send + Sync + 'static,
    H: Handlers<S> + 'static,
{
    let h = handlers.clone();
    let builder = builder.method(truenas_rpc::RpcMethod::new(truenas_rpc::MethodDef::new("login").doc("Authenticate a user; returns a session token.").audit_message("user login").secret_fields(["password"]).reply_capacity(118), move |request: LoginArgs, cx: &truenas_rpc::RequestCtx<S>| h.login(request, cx)))?;
    let h = handlers.clone();
    let builder = builder.method(truenas_rpc::RpcMethod::new(truenas_rpc::MethodDef::new("ping").doc("Liveness probe.").xdr(1001u32).reply_capacity(87), move |request: PingArgs, cx: &truenas_rpc::RequestCtx<S>| h.ping(request, cx)))?;
    let h = handlers.clone();
    let builder = builder.method(truenas_rpc::RpcMethod::new(truenas_rpc::MethodDef::new("crash").doc("Always raises (exercises the error-audit path).").audit_message("crash op").reply_capacity(87), move |request: CrashArgs, cx: &truenas_rpc::RequestCtx<S>| h.crash(request, cx)))?;
    let h = handlers.clone();
    let builder = builder.filterable(truenas_rpc::FilterableRpcMethod::<QueryArgs, Entry, _>::new(truenas_rpc::MethodDef::new("x.query").doc("Filterable query over a collection of entries.").reply_capacity(212), move |request: QueryArgs, cx: &truenas_rpc::RequestCtx<S>, filters: &truenas_rpc::CompiledFilters, options: &truenas_rpc::CompiledOptions| h.query(request, cx, filters, options)))?;
    let h = handlers.clone();
    let builder = builder.fd_transfer_method(truenas_rpc::RpcFdTransferMethod::<XferArgs, DownloadReady, DownloadDone, _, _>::new(truenas_rpc::MethodDef::new("x.download").doc("Raw-fd download (server produces the stream) with a typed $/transferReady interim.").reply_capacity(102), truenas_rpc::TransferDirection::Download, { let h = h.clone(); move |request: &XferArgs, cx: &truenas_rpc::RequestCtx<S>| h.download_ready(request, cx) }, move |request: XferArgs, ft: &dyn truenas_rpc::FileTransfer| h.download(request, ft)))?;
    let h = handlers.clone();
    let builder = builder.fd_transfer_method(truenas_rpc::RpcFdTransferMethod::<XferArgs, serde_json::Value, UploadDone, _, _>::new(truenas_rpc::MethodDef::new("x.upload").doc("Raw-fd upload (client produces the stream) with a free-form $/transferReady interim.").reply_capacity(106), truenas_rpc::TransferDirection::Upload, { let h = h.clone(); move |request: &XferArgs, cx: &truenas_rpc::RequestCtx<S>| h.upload_ready(request, cx) }, move |request: XferArgs, ft: &dyn truenas_rpc::FileTransfer| h.upload(request, ft)))?;
    let builder = builder.audit_sink(make_audit_sink::<S, _>(|_session: &truenas_rpc::Session<S>| truenas_audit::AuditPrincipal::default()));
    Ok(builder)
}

/// Build the spec-configured Linux kernel-audit sink with your identity extractor.
/// `register` installs one with an empty extractor by default; pass an extractor that reads your
/// session state and re-install via `.audit_sink(..)` to attribute records (`acct=`, uid, origin).
pub fn make_audit_sink<S, F>(identity: F) -> truenas_audit::LinuxAuditSink<S>
where
    S: Send + Sync + 'static,
    F: Fn(&truenas_rpc::Session<S>) -> truenas_audit::AuditPrincipal + Send + Sync + 'static,
{
    truenas_audit::LinuxAuditSink::<S>::builder("sample").identity(identity).build()
}

/// The wire protocols this service is served over (from the json-idl `protocols`).
pub const PROTOCOLS: &[&str] = &["json-rpc"];
