// GENERATED by truenas-rpc-codegen from tests/fixtures/sample — DO NOT EDIT BY HAND.
//
// A typed WebSocket client over the `truenas-rpc-tsclient` runtime: one method per plain
// `request -> result` RPC — encode the request, call the `$/negotiate`d connection, return the
// typed result. Subscription / filterable / transfer methods are not in this basic client.

import { RpcConnection, type Negotiated } from "truenas-rpc-tsclient";
import type { CrashArgs, LoginArgs, LoginResult, PingArgs, PingResult } from "./sample_types";

/** Typed WebSocket client for the "sample" service — connect with `SampleClient.connect(url)`. */
export class SampleClient {
  static readonly PROTOCOL = "sample";
  static readonly VERSION = "1.0.0";

  readonly #rpc: RpcConnection;

  /** Wrap an existing connection (advanced / BYO); prefer `connect`. */
  constructor(rpc: RpcConnection) {
    this.#rpc = rpc;
  }

  /** Open a WebSocket to `url` and `$/negotiate` this client's PROTOCOL. */
  static async connect(url: string): Promise<SampleClient> {
    return new SampleClient(await RpcConnection.connect(url, SampleClient.PROTOCOL));
  }

  /** The `$/negotiate` result (`{protocol, server, available}`), or null for a BYO connection. */
  get negotiated(): Negotiated | null {
    return this.#rpc.negotiated;
  }

  /** The protocol names the server offered at `$/negotiate` (discovery), or null. */
  get available(): string[] | null {
    return this.#rpc.available;
  }

  /** Authenticate a user; returns a session token. */
  async login(request: LoginArgs): Promise<LoginResult> {
    return this.#rpc.call("login", request) as Promise<LoginResult>;
  }

  /** Liveness probe. */
  async ping(request: PingArgs): Promise<PingResult> {
    return this.#rpc.call("ping", request) as Promise<PingResult>;
  }

  /** Always raises (exercises the error-audit path). */
  async crash(request: CrashArgs): Promise<PingResult> {
    return this.#rpc.call("crash", request) as Promise<PingResult>;
  }

  // x.query: filterable query — not in the basic client.

  // x.download: raw-fd transfer — not in the basic client.

  // x.upload: raw-fd transfer — not in the basic client.
}
