// GENERATED by truenas-rpc-codegen from tests/fixtures/sample — DO NOT EDIT BY HAND.
//
// A typed WebSocket client over the `truenas-rpc-tsclient` runtime: one method per plain
// `request -> result` RPC, a `subscribe_*` callback method per subscription, and `connect(url, auth?)`
// for session auth. Filterable / transfer methods are not in this basic client.

import { RpcConnection, JsonRpcError, type Negotiated, type Credential } from "truenas-rpc-tsclient";
import type { CrashArgs, LoginArgs, LoginResult, PingArgs, PingResult } from "./sample_types";

/** Typed WebSocket client for the "sample" service — connect with `SampleClient.connect(url)`. */
export class SampleClient {
  static readonly PROTOCOL = "sample";
  static readonly VERSION = "1.0.0";

  readonly #rpc: RpcConnection;

  /** Wrap an existing connection (advanced / BYO); prefer `connect`. */
  constructor(rpc: RpcConnection) {
    this.#rpc = rpc;
  }

  /** Open a WebSocket to `url`, `$/negotiate` this client's PROTOCOL, and — if `auth` is
   * given — authenticate the session (a non-`established` outcome throws). */
  static async connect(url: string, auth?: Credential): Promise<SampleClient> {
    const rpc = await RpcConnection.connect(url, SampleClient.PROTOCOL);
    if (auth !== undefined) {
      const outcome = await rpc.authenticate(auth);
      if (outcome.kind !== "established") {
        throw new JsonRpcError(-32000, "authentication " + outcome.kind);
      }
    }
    return new SampleClient(rpc);
  }

  /** The `$/negotiate` result (`{protocol, server, available}`), or null for a BYO connection. */
  get negotiated(): Negotiated | null {
    return this.#rpc.negotiated;
  }

  /** The protocol names the server offered at `$/negotiate` (discovery), or null. */
  get available(): string[] | null {
    return this.#rpc.available;
  }

  /** Authenticate a user; returns a session token. */
  async login(request: LoginArgs): Promise<LoginResult> {
    return this.#rpc.call("login", request) as Promise<LoginResult>;
  }

  /** Liveness probe. */
  async ping(request: PingArgs): Promise<PingResult> {
    return this.#rpc.call("ping", request) as Promise<PingResult>;
  }

  /** Always raises (exercises the error-audit path). */
  async crash(request: CrashArgs): Promise<PingResult> {
    return this.#rpc.call("crash", request) as Promise<PingResult>;
  }

  // x.query: filterable query — not in the basic client.

  // x.download: raw-fd transfer — not in the basic client.

  // x.upload: raw-fd transfer — not in the basic client.
}
