// GENERATED by truenas-rpc-codegen from tests/fixtures/sample — DO NOT EDIT BY HAND.
//
// The shared `$defs` types for the generated server (`Handlers`/`register`) and the typed client.

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct LoginArgs {
    pub user: String,
    pub password: truenas_rpc::Secret<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct LoginResult {
    pub token: truenas_rpc::Secret<String>,
    pub ok: bool,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct PingArgs {}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct PingResult {
    pub pong: bool,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct CrashArgs {}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Inner {
    pub x: i64,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Demo {
    pub name: String,
    #[serde(default)]
    pub count: i64,
    #[serde(default = "default_demo_ratio")]
    pub ratio: f64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    pub color: DemoColor,
    pub inner: Inner,
    pub api_key: truenas_rpc::Secret<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct QueryArgs {}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Entry {
    pub id: i64,
    pub name: String,
    pub ratio: f64,
    pub active: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct XferArgs {
    pub n: i64,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct DownloadReady {
    pub size: i64,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct DownloadDone {
    pub sent: i64,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct UploadDone {
    pub received: i64,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum DemoColor {
    #[serde(rename = "red")]
    Red,
    #[serde(rename = "green")]
    Green,
    #[serde(rename = "blue")]
    Blue,
}

fn default_demo_ratio() -> f64 { 1.5f64 }

