# GENERATED by truenas-rpc-codegen from tests/fixtures/sample — DO NOT EDIT BY HAND.
#
# A typed msgspec client over a raw byte transport (`truenas-rpc-pyclient`'s `RawClient`): each
# method encodes the request, calls the Rust engine, and decodes the typed result — reusing a
# shared `Encoder` + a per-method `Decoder` built once at import (not rebuilt per call).

from __future__ import annotations

from types import MappingProxyType

import msgspec
import truenas_rpc_pyclient

from sample_types import CrashArgs, LoginArgs, LoginResult, PingArgs, PingResult


_ENCODER = msgspec.json.Encoder()
_DECODERS: MappingProxyType[str, msgspec.json.Decoder] = MappingProxyType({
    "login": msgspec.json.Decoder(LoginResult),
    "ping": msgspec.json.Decoder(PingResult),
    "crash": msgspec.json.Decoder(PingResult),
})


class SampleClient:
    """Typed msgspec client for the "sample" service — the connection object: connect with
    `SampleClient.connect(endpoint)`, then call the protocol's methods on it."""

    PROTOCOL = "sample"
    VERSION = "1.0.0"

    def __init__(self, raw):
        """`raw` is the byte transport this client wraps (an internal detail; prefer `connect`)."""
        self._raw = raw
        self._negotiated = None

    @classmethod
    def connect(cls, endpoint):
        """Connect over AF_UNIX at `endpoint` and `$/negotiate` this client's `PROTOCOL`."""
        raw = truenas_rpc_pyclient.connect(endpoint, cls.PROTOCOL)
        obj = cls(raw)
        obj._negotiated = raw.negotiated()
        return obj

    @property
    def negotiated(self):
        """The `$/negotiate` result (`{'protocol', 'server', 'available'}`), or None for a BYO transport."""
        return self._negotiated

    @property
    def available(self):
        """The protocol names the server offered at `$/negotiate` (discovery), or None for a BYO transport."""
        return None if self._negotiated is None else self._negotiated["available"]

    def login(self, request: LoginArgs) -> LoginResult:
        """Authenticate a user; returns a session token."""
        return _DECODERS["login"].decode(
            self._raw.call("login", _ENCODER.encode(request))
        )

    def ping(self, request: PingArgs) -> PingResult:
        """Liveness probe."""
        return _DECODERS["ping"].decode(
            self._raw.call("ping", _ENCODER.encode(request))
        )

    def crash(self, request: CrashArgs) -> PingResult:
        """Always raises (exercises the error-audit path)."""
        return _DECODERS["crash"].decode(
            self._raw.call("crash", _ENCODER.encode(request))
        )

    # x.query: filterable query — not in the basic msgspec client.
    # x.download: raw-fd transfer — not in the basic msgspec client.
    # x.upload: raw-fd transfer — not in the basic msgspec client.
