# GENERATED by truenas-rpc-codegen from tests/fixtures/sample — DO NOT EDIT BY HAND.
#
# The msgspec API types (one class per `$defs`), the generated `StrEnum`s, and a `METHODS` table
# (wire name -> (Params, Result)) shared by the generated client and the server-dispatch shim.

from __future__ import annotations

import enum
from types import MappingProxyType
from typing import Annotated

import msgspec


class DemoColor(enum.StrEnum):
    RED = "red"
    GREEN = "green"
    BLUE = "blue"


class LoginArgs(msgspec.Struct):
    user: str
    password: Annotated[str, msgspec.Meta(extra={"secret": True})]


class LoginResult(msgspec.Struct):
    token: Annotated[str, msgspec.Meta(extra={"secret": True})]
    ok: bool


class PingArgs(msgspec.Struct):
    pass


class PingResult(msgspec.Struct):
    pong: bool


class CrashArgs(msgspec.Struct):
    pass


class Inner(msgspec.Struct):
    x: int


class Demo(msgspec.Struct):
    name: str
    color: DemoColor
    inner: Inner
    api_key: Annotated[str, msgspec.Meta(extra={"secret": True})]
    count: int = 0
    ratio: float = 1.5
    note: str | None = None
    tags: list[str] | None = None


class QueryArgs(msgspec.Struct):
    pass


class Entry(msgspec.Struct):
    id: int
    name: str
    ratio: float
    active: bool
    note: str | None = None


class XferArgs(msgspec.Struct):
    n: int


class DownloadReady(msgspec.Struct):
    size: int


class DownloadDone(msgspec.Struct):
    sent: int


class UploadDone(msgspec.Struct):
    received: int


METHODS: MappingProxyType[str, tuple[type, type]] = MappingProxyType({
    "login": (LoginArgs, LoginResult),
    "ping": (PingArgs, PingResult),
    "crash": (CrashArgs, PingResult),
})
