// GENERATED by truenas-rpc-codegen from tests/fixtures/sample — DO NOT EDIT BY HAND.
//
// The TypeScript API types: one `interface` per `$defs`, a string-union `type` per enum. Imported
// by the generated client; safe to import on their own for a types-only consumer.

export type DemoColor = "red" | "green" | "blue";

export interface LoginArgs {
  user: string;
  /** secret */
  password: string;
}

export interface LoginResult {
  /** secret */
  token: string;
  ok: boolean;
}

export interface PingArgs {}

export interface PingResult {
  pong: boolean;
}

export interface CrashArgs {}

export interface Inner {
  x: number;
}

export interface Demo {
  name: string;
  count?: number;
  ratio?: number;
  note?: string | null;
  tags?: string[] | null;
  color: DemoColor;
  inner: Inner;
  /** secret */
  api_key: string;
}

export interface QueryArgs {}

export interface Entry {
  id: number;
  name: string;
  ratio: number;
  active: boolean;
  note?: string | null;
}

export interface XferArgs {
  n: number;
}

export interface DownloadReady {
  size: number;
}

export interface DownloadDone {
  sent: number;
}

export interface UploadDone {
  received: number;
}
