// GENERATED by truenas-rpc-codegen from tests/fixtures/sample — DO NOT EDIT BY HAND.
//
// A PyO3 extension module: typed request/response classes + a client wrapping the generated Rust
// typed client. Depends on `truenas-rpc-pyclient` + `pyo3` + the generated types & client.

#[pyo3::pyclass(name = "LoginArgs")]
#[derive(Clone)]
pub struct PyLoginArgs {
    inner: LoginArgs,
}

#[pyo3::pymethods]
impl PyLoginArgs {
    #[new]
    #[pyo3(signature = (**kwargs))]
    fn new(py: pyo3::Python<'_>, kwargs: Option<pyo3::Bound<'_, pyo3::types::PyDict>>) -> pyo3::PyResult<Self> {
        let dict = match kwargs { Some(kwargs) => kwargs, None => pyo3::types::PyDict::new(py) };
        Ok(PyLoginArgs { inner: truenas_rpc_pyclient::from_py(dict.as_any())? })
    }
    #[getter]
    fn get_user(&self, py: pyo3::Python<'_>) -> pyo3::PyResult<pyo3::PyObject> {
        truenas_rpc_pyclient::to_py(py, &self.inner.user)
    }
    #[getter]
    fn get_password(&self, py: pyo3::Python<'_>) -> pyo3::PyResult<pyo3::PyObject> {
        truenas_rpc_pyclient::to_py(py, &self.inner.password)
    }
    fn __repr__(&self) -> String {
        format!("LoginArgs({:?})", self.inner)
    }
}

#[pyo3::pyclass(name = "LoginResult")]
#[derive(Clone)]
pub struct PyLoginResult {
    inner: LoginResult,
}

#[pyo3::pymethods]
impl PyLoginResult {
    #[new]
    #[pyo3(signature = (**kwargs))]
    fn new(py: pyo3::Python<'_>, kwargs: Option<pyo3::Bound<'_, pyo3::types::PyDict>>) -> pyo3::PyResult<Self> {
        let dict = match kwargs { Some(kwargs) => kwargs, None => pyo3::types::PyDict::new(py) };
        Ok(PyLoginResult { inner: truenas_rpc_pyclient::from_py(dict.as_any())? })
    }
    #[getter]
    fn get_token(&self, py: pyo3::Python<'_>) -> pyo3::PyResult<pyo3::PyObject> {
        truenas_rpc_pyclient::to_py(py, &self.inner.token)
    }
    #[getter]
    fn get_ok(&self, py: pyo3::Python<'_>) -> pyo3::PyResult<pyo3::PyObject> {
        truenas_rpc_pyclient::to_py(py, &self.inner.ok)
    }
    fn __repr__(&self) -> String {
        format!("LoginResult({:?})", self.inner)
    }
}

#[pyo3::pyclass(name = "PingArgs")]
#[derive(Clone)]
pub struct PyPingArgs {
    inner: PingArgs,
}

#[pyo3::pymethods]
impl PyPingArgs {
    #[new]
    #[pyo3(signature = (**kwargs))]
    fn new(py: pyo3::Python<'_>, kwargs: Option<pyo3::Bound<'_, pyo3::types::PyDict>>) -> pyo3::PyResult<Self> {
        let dict = match kwargs { Some(kwargs) => kwargs, None => pyo3::types::PyDict::new(py) };
        Ok(PyPingArgs { inner: truenas_rpc_pyclient::from_py(dict.as_any())? })
    }
    fn __repr__(&self) -> String {
        format!("PingArgs({:?})", self.inner)
    }
}

#[pyo3::pyclass(name = "PingResult")]
#[derive(Clone)]
pub struct PyPingResult {
    inner: PingResult,
}

#[pyo3::pymethods]
impl PyPingResult {
    #[new]
    #[pyo3(signature = (**kwargs))]
    fn new(py: pyo3::Python<'_>, kwargs: Option<pyo3::Bound<'_, pyo3::types::PyDict>>) -> pyo3::PyResult<Self> {
        let dict = match kwargs { Some(kwargs) => kwargs, None => pyo3::types::PyDict::new(py) };
        Ok(PyPingResult { inner: truenas_rpc_pyclient::from_py(dict.as_any())? })
    }
    #[getter]
    fn get_pong(&self, py: pyo3::Python<'_>) -> pyo3::PyResult<pyo3::PyObject> {
        truenas_rpc_pyclient::to_py(py, &self.inner.pong)
    }
    fn __repr__(&self) -> String {
        format!("PingResult({:?})", self.inner)
    }
}

#[pyo3::pyclass(name = "CrashArgs")]
#[derive(Clone)]
pub struct PyCrashArgs {
    inner: CrashArgs,
}

#[pyo3::pymethods]
impl PyCrashArgs {
    #[new]
    #[pyo3(signature = (**kwargs))]
    fn new(py: pyo3::Python<'_>, kwargs: Option<pyo3::Bound<'_, pyo3::types::PyDict>>) -> pyo3::PyResult<Self> {
        let dict = match kwargs { Some(kwargs) => kwargs, None => pyo3::types::PyDict::new(py) };
        Ok(PyCrashArgs { inner: truenas_rpc_pyclient::from_py(dict.as_any())? })
    }
    fn __repr__(&self) -> String {
        format!("CrashArgs({:?})", self.inner)
    }
}

#[pyo3::pyclass(name = "Inner")]
#[derive(Clone)]
pub struct PyInner {
    inner: Inner,
}

#[pyo3::pymethods]
impl PyInner {
    #[new]
    #[pyo3(signature = (**kwargs))]
    fn new(py: pyo3::Python<'_>, kwargs: Option<pyo3::Bound<'_, pyo3::types::PyDict>>) -> pyo3::PyResult<Self> {
        let dict = match kwargs { Some(kwargs) => kwargs, None => pyo3::types::PyDict::new(py) };
        Ok(PyInner { inner: truenas_rpc_pyclient::from_py(dict.as_any())? })
    }
    #[getter]
    fn get_x(&self, py: pyo3::Python<'_>) -> pyo3::PyResult<pyo3::PyObject> {
        truenas_rpc_pyclient::to_py(py, &self.inner.x)
    }
    fn __repr__(&self) -> String {
        format!("Inner({:?})", self.inner)
    }
}

#[pyo3::pyclass(name = "Demo")]
#[derive(Clone)]
pub struct PyDemo {
    inner: Demo,
}

#[pyo3::pymethods]
impl PyDemo {
    #[new]
    #[pyo3(signature = (**kwargs))]
    fn new(py: pyo3::Python<'_>, kwargs: Option<pyo3::Bound<'_, pyo3::types::PyDict>>) -> pyo3::PyResult<Self> {
        let dict = match kwargs { Some(kwargs) => kwargs, None => pyo3::types::PyDict::new(py) };
        Ok(PyDemo { inner: truenas_rpc_pyclient::from_py(dict.as_any())? })
    }
    #[getter]
    fn get_name(&self, py: pyo3::Python<'_>) -> pyo3::PyResult<pyo3::PyObject> {
        truenas_rpc_pyclient::to_py(py, &self.inner.name)
    }
    #[getter]
    fn get_count(&self, py: pyo3::Python<'_>) -> pyo3::PyResult<pyo3::PyObject> {
        truenas_rpc_pyclient::to_py(py, &self.inner.count)
    }
    #[getter]
    fn get_ratio(&self, py: pyo3::Python<'_>) -> pyo3::PyResult<pyo3::PyObject> {
        truenas_rpc_pyclient::to_py(py, &self.inner.ratio)
    }
    #[getter]
    fn get_note(&self, py: pyo3::Python<'_>) -> pyo3::PyResult<pyo3::PyObject> {
        truenas_rpc_pyclient::to_py(py, &self.inner.note)
    }
    #[getter]
    fn get_tags(&self, py: pyo3::Python<'_>) -> pyo3::PyResult<pyo3::PyObject> {
        truenas_rpc_pyclient::to_py(py, &self.inner.tags)
    }
    #[getter]
    fn get_color(&self, py: pyo3::Python<'_>) -> pyo3::PyResult<pyo3::PyObject> {
        truenas_rpc_pyclient::to_py(py, &self.inner.color)
    }
    #[getter]
    fn get_inner(&self, py: pyo3::Python<'_>) -> pyo3::PyResult<pyo3::PyObject> {
        truenas_rpc_pyclient::to_py(py, &self.inner.inner)
    }
    #[getter]
    fn get_api_key(&self, py: pyo3::Python<'_>) -> pyo3::PyResult<pyo3::PyObject> {
        truenas_rpc_pyclient::to_py(py, &self.inner.api_key)
    }
    fn __repr__(&self) -> String {
        format!("Demo({:?})", self.inner)
    }
}

#[pyo3::pyclass(name = "QueryArgs")]
#[derive(Clone)]
pub struct PyQueryArgs {
    inner: QueryArgs,
}

#[pyo3::pymethods]
impl PyQueryArgs {
    #[new]
    #[pyo3(signature = (**kwargs))]
    fn new(py: pyo3::Python<'_>, kwargs: Option<pyo3::Bound<'_, pyo3::types::PyDict>>) -> pyo3::PyResult<Self> {
        let dict = match kwargs { Some(kwargs) => kwargs, None => pyo3::types::PyDict::new(py) };
        Ok(PyQueryArgs { inner: truenas_rpc_pyclient::from_py(dict.as_any())? })
    }
    fn __repr__(&self) -> String {
        format!("QueryArgs({:?})", self.inner)
    }
}

#[pyo3::pyclass(name = "Entry")]
#[derive(Clone)]
pub struct PyEntry {
    inner: Entry,
}

#[pyo3::pymethods]
impl PyEntry {
    #[new]
    #[pyo3(signature = (**kwargs))]
    fn new(py: pyo3::Python<'_>, kwargs: Option<pyo3::Bound<'_, pyo3::types::PyDict>>) -> pyo3::PyResult<Self> {
        let dict = match kwargs { Some(kwargs) => kwargs, None => pyo3::types::PyDict::new(py) };
        Ok(PyEntry { inner: truenas_rpc_pyclient::from_py(dict.as_any())? })
    }
    #[getter]
    fn get_id(&self, py: pyo3::Python<'_>) -> pyo3::PyResult<pyo3::PyObject> {
        truenas_rpc_pyclient::to_py(py, &self.inner.id)
    }
    #[getter]
    fn get_name(&self, py: pyo3::Python<'_>) -> pyo3::PyResult<pyo3::PyObject> {
        truenas_rpc_pyclient::to_py(py, &self.inner.name)
    }
    #[getter]
    fn get_ratio(&self, py: pyo3::Python<'_>) -> pyo3::PyResult<pyo3::PyObject> {
        truenas_rpc_pyclient::to_py(py, &self.inner.ratio)
    }
    #[getter]
    fn get_active(&self, py: pyo3::Python<'_>) -> pyo3::PyResult<pyo3::PyObject> {
        truenas_rpc_pyclient::to_py(py, &self.inner.active)
    }
    #[getter]
    fn get_note(&self, py: pyo3::Python<'_>) -> pyo3::PyResult<pyo3::PyObject> {
        truenas_rpc_pyclient::to_py(py, &self.inner.note)
    }
    fn __repr__(&self) -> String {
        format!("Entry({:?})", self.inner)
    }
}

#[pyo3::pyclass(name = "XferArgs")]
#[derive(Clone)]
pub struct PyXferArgs {
    inner: XferArgs,
}

#[pyo3::pymethods]
impl PyXferArgs {
    #[new]
    #[pyo3(signature = (**kwargs))]
    fn new(py: pyo3::Python<'_>, kwargs: Option<pyo3::Bound<'_, pyo3::types::PyDict>>) -> pyo3::PyResult<Self> {
        let dict = match kwargs { Some(kwargs) => kwargs, None => pyo3::types::PyDict::new(py) };
        Ok(PyXferArgs { inner: truenas_rpc_pyclient::from_py(dict.as_any())? })
    }
    #[getter]
    fn get_n(&self, py: pyo3::Python<'_>) -> pyo3::PyResult<pyo3::PyObject> {
        truenas_rpc_pyclient::to_py(py, &self.inner.n)
    }
    fn __repr__(&self) -> String {
        format!("XferArgs({:?})", self.inner)
    }
}

#[pyo3::pyclass(name = "DownloadReady")]
#[derive(Clone)]
pub struct PyDownloadReady {
    inner: DownloadReady,
}

#[pyo3::pymethods]
impl PyDownloadReady {
    #[new]
    #[pyo3(signature = (**kwargs))]
    fn new(py: pyo3::Python<'_>, kwargs: Option<pyo3::Bound<'_, pyo3::types::PyDict>>) -> pyo3::PyResult<Self> {
        let dict = match kwargs { Some(kwargs) => kwargs, None => pyo3::types::PyDict::new(py) };
        Ok(PyDownloadReady { inner: truenas_rpc_pyclient::from_py(dict.as_any())? })
    }
    #[getter]
    fn get_size(&self, py: pyo3::Python<'_>) -> pyo3::PyResult<pyo3::PyObject> {
        truenas_rpc_pyclient::to_py(py, &self.inner.size)
    }
    fn __repr__(&self) -> String {
        format!("DownloadReady({:?})", self.inner)
    }
}

#[pyo3::pyclass(name = "DownloadDone")]
#[derive(Clone)]
pub struct PyDownloadDone {
    inner: DownloadDone,
}

#[pyo3::pymethods]
impl PyDownloadDone {
    #[new]
    #[pyo3(signature = (**kwargs))]
    fn new(py: pyo3::Python<'_>, kwargs: Option<pyo3::Bound<'_, pyo3::types::PyDict>>) -> pyo3::PyResult<Self> {
        let dict = match kwargs { Some(kwargs) => kwargs, None => pyo3::types::PyDict::new(py) };
        Ok(PyDownloadDone { inner: truenas_rpc_pyclient::from_py(dict.as_any())? })
    }
    #[getter]
    fn get_sent(&self, py: pyo3::Python<'_>) -> pyo3::PyResult<pyo3::PyObject> {
        truenas_rpc_pyclient::to_py(py, &self.inner.sent)
    }
    fn __repr__(&self) -> String {
        format!("DownloadDone({:?})", self.inner)
    }
}

#[pyo3::pyclass(name = "UploadDone")]
#[derive(Clone)]
pub struct PyUploadDone {
    inner: UploadDone,
}

#[pyo3::pymethods]
impl PyUploadDone {
    #[new]
    #[pyo3(signature = (**kwargs))]
    fn new(py: pyo3::Python<'_>, kwargs: Option<pyo3::Bound<'_, pyo3::types::PyDict>>) -> pyo3::PyResult<Self> {
        let dict = match kwargs { Some(kwargs) => kwargs, None => pyo3::types::PyDict::new(py) };
        Ok(PyUploadDone { inner: truenas_rpc_pyclient::from_py(dict.as_any())? })
    }
    #[getter]
    fn get_received(&self, py: pyo3::Python<'_>) -> pyo3::PyResult<pyo3::PyObject> {
        truenas_rpc_pyclient::to_py(py, &self.inner.received)
    }
    fn __repr__(&self) -> String {
        format!("UploadDone({:?})", self.inner)
    }
}

#[pyo3::pyclass(name = "SampleClient")]
pub struct PySampleClient {
    inner: std::sync::Mutex<Option<SampleClient<truenas_rpc_client::JsonRpcClient>>>,
}

#[pyo3::pymethods]
impl PySampleClient {
    /// Connect to `endpoint` and negotiate the `sample` protocol.
    #[staticmethod]
    #[pyo3(signature = (endpoint, config = None))]
    fn connect(py: pyo3::Python<'_>, endpoint: &truenas_rpc_pyclient::PyEndpoint, config: Option<&truenas_rpc_pyclient::PyClientConfig>) -> pyo3::PyResult<Self> {
        let engine = truenas_rpc_pyclient::connect_blocking(py, endpoint.inner(), "sample", config.map(|c| c.inner()))?;
        Ok(PySampleClient { inner: std::sync::Mutex::new(Some(SampleClient::new(engine))) })
    }
    /// Call `login`.
    fn login(&self, py: pyo3::Python<'_>, request: &PyLoginArgs) -> pyo3::PyResult<PyLoginResult> {
        let request = request.inner.clone();
        let guard = self.inner.lock().expect("client mutex");
        let client = guard.as_ref().ok_or_else(|| truenas_rpc_pyclient::RpcError::new_err("client is closed"))?;
        let out = py.allow_threads(|| truenas_rpc_pyclient::runtime().block_on(client.login(request)));
        out.map(|inner| PyLoginResult { inner }).map_err(truenas_rpc_pyclient::map_call_err)
    }
    /// Call `ping`.
    fn ping(&self, py: pyo3::Python<'_>, request: &PyPingArgs) -> pyo3::PyResult<PyPingResult> {
        let request = request.inner.clone();
        let guard = self.inner.lock().expect("client mutex");
        let client = guard.as_ref().ok_or_else(|| truenas_rpc_pyclient::RpcError::new_err("client is closed"))?;
        let out = py.allow_threads(|| truenas_rpc_pyclient::runtime().block_on(client.ping(request)));
        out.map(|inner| PyPingResult { inner }).map_err(truenas_rpc_pyclient::map_call_err)
    }
    /// Call `crash`.
    fn crash(&self, py: pyo3::Python<'_>, request: &PyCrashArgs) -> pyo3::PyResult<PyPingResult> {
        let request = request.inner.clone();
        let guard = self.inner.lock().expect("client mutex");
        let client = guard.as_ref().ok_or_else(|| truenas_rpc_pyclient::RpcError::new_err("client is closed"))?;
        let out = py.allow_threads(|| truenas_rpc_pyclient::runtime().block_on(client.crash(request)));
        out.map(|inner| PyPingResult { inner }).map_err(truenas_rpc_pyclient::map_call_err)
    }
    // `x.query`: filterable query — not in the basic Python client.
    // `x.download`: raw-fd transfer — not in the basic Python client.
    // `x.upload`: raw-fd transfer — not in the basic Python client.
    /// Disconnect (drops the connection — a hard close, no `$/sessionClose`).
    fn close(&self) -> pyo3::PyResult<()> {
        let _ = self.inner.lock().expect("client mutex").take();
        Ok(())
    }
}


/// The generated Python extension module. Also callable directly (e.g. from a test)
/// to populate a `PyModule` with the classes.
#[pyo3::pymodule]
#[pyo3(name = "sample")]
pub fn sample(m: &pyo3::Bound<'_, pyo3::types::PyModule>) -> pyo3::PyResult<()> {
    use pyo3::types::PyModuleMethods;
    truenas_rpc_pyclient::register_common(m)?;
    m.add_class::<PyLoginArgs>()?;
    m.add_class::<PyLoginResult>()?;
    m.add_class::<PyPingArgs>()?;
    m.add_class::<PyPingResult>()?;
    m.add_class::<PyCrashArgs>()?;
    m.add_class::<PyInner>()?;
    m.add_class::<PyDemo>()?;
    m.add_class::<PyQueryArgs>()?;
    m.add_class::<PyEntry>()?;
    m.add_class::<PyXferArgs>()?;
    m.add_class::<PyDownloadReady>()?;
    m.add_class::<PyDownloadDone>()?;
    m.add_class::<PyUploadDone>()?;
    m.add_class::<PySampleClient>()?;
    Ok(())
}
