# GENERATED by truenas-rpc-codegen from tests/fixtures/sample — DO NOT EDIT BY HAND.
#
# The python-method dispatch framework the embedded bridge drives. Register a handler with
# `@method("<wire>")`; it receives `(request, ctx)` and returns a result the framework encodes.

from __future__ import annotations

from collections.abc import Callable
from types import MappingProxyType
from typing import Any

import msgspec

from sample_types import METHODS


class RpcError(Exception):
    """Raise from a handler to return a JSON-RPC error (`code` + `message`) to the caller."""

    def __init__(self, code: int, message: str) -> None:
        super().__init__(message)
        self.code = code
        self.message = message


class Context:
    """Per-call context handed to a handler.

    ``session`` is the session-state view (raw JSON bytes); ``call`` is the in-process caller
    ``call(name: str, params: bytes, elevated: bool = False) -> bytes`` that routes back into the core
    (raising ``RuntimeError((code, message))`` on a core error); set ``audit`` to a str to attach a
    runtime audit detail.
    """

    def __init__(self, session: bytes, call: Callable[..., bytes]) -> None:
        self.session = session
        self.call = call
        self.audit: str | None = None


_HANDLERS: dict[str, Callable[..., object]] = {}

# A decoder per method's params type + one shared encoder, built once from METHODS and reused every
# call (msgspec's one-shot ``json.decode``/``encode`` rebuild these each time). A read-only proxy —
# the keys mirror METHODS, so a lookup miss is "method not found".
_DECODERS: MappingProxyType[str, msgspec.json.Decoder[Any]] = MappingProxyType(
    {name: msgspec.json.Decoder(params) for name, (params, _result) in METHODS.items()}
)
_ENCODER = msgspec.json.Encoder()


def method(name: str) -> Callable[[Callable[..., object]], Callable[..., object]]:
    """Register the decorated ``handler(request, ctx)`` for the python:true method ``name``."""

    def register(fn: Callable[..., object]) -> Callable[..., object]:
        _HANDLERS[name] = fn
        return fn

    return register


def dispatch(name: str, params: bytes, session: bytes, call: Callable[..., bytes]) -> tuple[int, bytes, bytes]:
    """The embedded-bridge entry point: look up the method, decode ``params`` by its type, run the
    handler, and encode the result. Returns ``(status, payload, audit)`` — status ``0`` with the
    result JSON as payload, or a JSON-RPC error ``code`` with the message as payload."""
    decoder = _DECODERS.get(name)
    handler = _HANDLERS.get(name)
    if decoder is None or handler is None:
        return (-32601, b"Method not found", b"")
    try:
        request = decoder.decode(params)
    except (msgspec.ValidationError, msgspec.DecodeError) as exc:
        return (-32602, str(exc).encode(), b"")
    ctx = Context(session, call)
    try:
        result = handler(request, ctx)
    except RpcError as exc:
        return (exc.code, str(exc.message).encode(), b"")
    audit = ctx.audit.encode() if ctx.audit else b""
    return (0, _ENCODER.encode(result), audit)
