// GENERATED by truenas-rpc-codegen from tests/fixtures/sample — DO NOT EDIT BY HAND.
//
// A typed async client over a `truenas_rpc_client::CallEngine` (e.g. a `JsonRpcClient`).

pub struct SampleClient<E> {
    engine: E,
}

impl<E: truenas_rpc_client::CallEngine> SampleClient<E> {
    /// Wrap a [`CallEngine`](truenas_rpc_client::CallEngine) — e.g. a connected
    /// `truenas_rpc_client::JsonRpcClient` (after `$/negotiate`).
    pub fn new(engine: E) -> Self {
        Self { engine }
    }

    /// Call `login`.
    pub async fn login(&self, request: LoginArgs) -> Result<LoginResult, truenas_rpc::JsonRpcError> {
        let params = serde_json::to_vec(&request).map_err(|e| truenas_rpc::JsonRpcError::invalid_params(e.to_string()))?;
        let bytes = self.engine.call(truenas_rpc_client::MethodKey::Name("login"), &params).await?;
        serde_json::from_slice(&bytes).map_err(|e| truenas_rpc::JsonRpcError::internal(e.to_string()))
    }
    /// Call `ping`.
    pub async fn ping(&self, request: PingArgs) -> Result<PingResult, truenas_rpc::JsonRpcError> {
        let params = serde_json::to_vec(&request).map_err(|e| truenas_rpc::JsonRpcError::invalid_params(e.to_string()))?;
        let bytes = self.engine.call(truenas_rpc_client::MethodKey::Name("ping"), &params).await?;
        serde_json::from_slice(&bytes).map_err(|e| truenas_rpc::JsonRpcError::internal(e.to_string()))
    }
    /// Call `crash`.
    pub async fn crash(&self, request: CrashArgs) -> Result<PingResult, truenas_rpc::JsonRpcError> {
        let params = serde_json::to_vec(&request).map_err(|e| truenas_rpc::JsonRpcError::invalid_params(e.to_string()))?;
        let bytes = self.engine.call(truenas_rpc_client::MethodKey::Name("crash"), &params).await?;
        serde_json::from_slice(&bytes).map_err(|e| truenas_rpc::JsonRpcError::internal(e.to_string()))
    }
    /// Filterable query `x.query`.
    pub async fn query(&self, request: QueryArgs, query_filters: Option<truenas_rpc::QueryFilters>, query_options: Option<truenas_rpc::QueryOptions>) -> Result<truenas_rpc_client::QueryResult<Entry>, truenas_rpc::JsonRpcError> {
        let mut value = serde_json::to_value(&request).map_err(|e| truenas_rpc::JsonRpcError::invalid_params(e.to_string()))?;
        let obj = value.as_object_mut().ok_or_else(|| truenas_rpc::JsonRpcError::invalid_params("query params must be an object"))?;
        if let Some(f) = query_filters { obj.insert("query-filters".to_string(), serde_json::to_value(f).map_err(|e| truenas_rpc::JsonRpcError::invalid_params(e.to_string()))?); }
        if let Some(o) = query_options { obj.insert("query-options".to_string(), serde_json::to_value(o).map_err(|e| truenas_rpc::JsonRpcError::invalid_params(e.to_string()))?); }
        let params = serde_json::to_vec(&value).map_err(|e| truenas_rpc::JsonRpcError::invalid_params(e.to_string()))?;
        let bytes = self.engine.call(truenas_rpc_client::MethodKey::Name("x.query"), &params).await?;
        serde_json::from_slice(&bytes).map_err(|e| truenas_rpc::JsonRpcError::internal(e.to_string()))
    }
}
